spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java
=> Fix CCF Javadocs For CacheMode.CONNECTION

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/log4j/AmqpAppenderIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-474
Instead of replacing the placeholder on every log event,
replace it once during initialization.
=> AMQP-474:Log Appenders appId Replacement Once Only

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ChannelProxy.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-139
=> AMQP-139: Expose isTransactional() on Channel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractRoutingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RoutingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java
JIRA: https://jira.spring.io/browse/AMQP-494
__cherry-pick to 1.4.x__
=> AMQP-494: Extract RoutingConnectionFactory Iface

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistrar.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitTests.java
JIRA: https://jira.spring.io/browse/AMQP-481
Previously the `@Lazy` components haven't been registered with `MessageListenerContainer`,
because `RabbitListenerEndpointRegistrar` has done that from its `afterPropertiesSet()`.
Add logic to `registerListenerContainer` on demand from the `RabbitListenerEndpointRegistrar#registerEndpoint`
**Cherry-pick to 1.4.x**
=> AMQP-481: Register `@RabbitListener` for `@Lazy`

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/core/AmqpMessageReturnedException.java, spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/AbstractDecompressingPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/DelegatingDecompressingPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/GUnzipPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/GZipPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/MessagePostProcessorUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitResourceHolder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-515
Also revert jacoco version for Sonar compatibility.
Some Major Violations
Fix Package Tangle
=> AMQP-515: Eliminate new Sonar Critical Violations

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerPlaceholderParserTests.java
JIRA: https://jira.spring.io/browse/AMQP-519
=> AMQP-519: Shut Down Deferred Close Executor

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-532
Properly use the iterator to remove the entries.
__cherry-pick to 1.4.x__
=> AMQP-532: Fix Pub.Conf. Nacks on close()

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-551
Perform all mock creation/interaction on the main thread.
=> AMQP-551: Fix Mockito Usage in Failover Tests

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java
JIRA: https://jira.spring.io/browse/AMQP-558
New methods on `Channel`.
__do not resolve JIRA__
After this is merged, we'll release 1.5.3, then make master 1.6, then bump amqp-client to 3.6.0.
=> AMQP-558: amqp-client 3.5.7 + 3.6.0 Compatibility

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
http://stackoverflow.com/questions/34454159/how-to-write-an-integration-test-for-rabbitlistener-annotation
=> SO34454159: Test Showing Proxying a RabbitListener

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpReplyTimeoutException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/DeclarationExceptionEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/DeclareExchangeConnectionListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdminEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ListenerContainerIdleEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/package-info.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIdleContainerTests.java
Package:
Async template references core and listener packages - needs to move up a level.
DeclareExchangeExceptionListener
AmqpReplyTimeoutException
Classes:
Admin Event
Container Event
=> Fix Tangles

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParser.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-1.6.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml
JIRA: https://jira.spring.io/browse/AMQP-592
=> AMQP-592: CCF factory-timeout and connection-limit

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-595
Ignore container's auto-startup once the context is refreshed.
__cherry-pick to 1.5.x__
=> AMQP-595: Fix Auto-Startup for @RabbitListener

spring-rabbit/src/main/resources/META-INF/spring.schemas
_I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement._
=> Fix namespace mapping (META-INF/spring.schemas)

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-572
Since RabbitMQ doesn't support XA transactions and it really doesn't care about the transaction boundaries,
it doesn't matter when we call `channel.basicAck()` and `channel.txCommit()`.
Therefore any `TransactionManager` looks the same for RabbitMQ and we don't need to distinguish if we are within a local transaction or XA.
* Move `this.resourceHolder.commitAll()` in the `RabbitResourceSynchronization` to the `afterCompletion()` permanently, unconditionally.
* All test passes and now the ACK on the RabbitMQ will be done only if the commit to the DB is successful, for example.
* And it doesn't matter now if we use  XA transactions or Dave Syer's `Best Efforts 1PC pattern` with the `ChainedTransactionManager`
NOTE: There might be some breaking …
=> AMQP-572: Always commit only in `afterCompletion`

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/core/AbstractDeclarable.java, spring-amqp/src/main/java/org/springframework/amqp/core/Declarable.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/Exchange.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/Queue.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/QueueBinding.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/BindingFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/NamespaceUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-1.6.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AbstractRabbitAnnotationDrivenTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AnnotationDrivenNamespaceTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/annotation-driven-sample-config.xml, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-609
Also `ignoreDeclarationExceptions`.
=> AMQP-609: Add 'internal' to @Exhange

build.gradle
JIRA: https://jira.spring.io/browse/AMQP-611
=> AMQP-611: Upgrade to Log4J2-2.5

build.gradle, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePerformanceIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerMultipleQueueIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerManualAckIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryCachingConnectionIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryRepeatIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerTxSizeIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/test/Log4jLevelAdjuster.java
JIRA: https://jira.spring.io/browse/AMQP-630
=> AMQP-630: Move dependency from Log4j to Log4j2

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
JIRA: https://jira.spring.io/browse/AMQP-633
Close connection for non-transactional template.
=> AMQP-633: Ensure Resources are Closed

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ClientRecoveryCompatibilityTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SingleConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateHeaderTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/LocallyTransactedTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
JIRA: https://jira.spring.io/browse/AMQP-631
=> AMQP-631: Fix mocks test for new method in charge

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java
https://github.com/spring-projects/spring-boot/issues/7136#issuecomment-252899474
=> Support spring-retry 1.2

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-661
=> AMQP-661: NPE with null Queue Names in Container

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
JIRA: https://jira.spring.io/browse/AMQP-663
The test is waiting for the consumer to be refreshed after deleting a queue by
inspecting the consumers map. There is a short period where the map is empty and
the test does not protect for that when iterating. Adding hasNext() won't help -
it will reduce the probability but won't eliminate it.
Catch the NoSuchElementException in the while loop and continue to wait.
__cherry-pick to 1.6.x, 1.5.x__
=> AMQP-663: Fix Race in Container Test

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
https://sonar.spring.io/issues/search#componentRoots=org.springframework.amqp%3Aspring-amqp-dist|createdAt=2016-10-22T02%3A35%3A37%2B0000|sort=UPDATE_DATE|asc=false
https://sonar.spring.io/issues/search#componentRoots=org.springframework.amqp%3Aspring-amqp-dist|createdAt=2016-10-23T02%3A34%3A53%2B0000|sort=UPDATE_DATE|asc=false
=> Fix New Sonar Issues

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java
JIRA: https://jira.spring.io/browse/AMQP-674
=> AMQP-674: Resolve deprecation in `AmqpAppender`

spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.0.xsd, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
=> DMLC - Doc Polishing

spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/RabbitListenerTestHarness.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleResourceHolder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java
Fixes https://jira.spring.io/browse/AMQP-685
=> AMQP-685: Use Supplier variants of Spring-Framework's core Assert utility

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java
JIRA: https://jira.spring.io/browse/AMQP-691
Log an error if the layout is missing.
Use the default platform charset if none is supplied.
__cherry-pick to 1.7.x, master__
=> AMQP-691: Detect Missing Logback Layout

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java
Move assert - avoid the race which would cause an NPE if the template is stopped while a send is in process.
Remove the pending future in this case.
=> AMQP-693: Polishing

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplate.java
JIRA: https://jira.spring.io/browse/AMQP-698
Guard for null returns from native client.
__cherry-pick to 1.7.x, 1.6.x__
=> AMQP-698: Fix NPE in RabbitManagementTemplate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
JIRA: https://jira.spring.io/browse/AMQP-704
The template did not check for null before converting to String.
=> AMQP-704: Fix RabbitTemplate Reply NPE

build.gradle
JIRA: https://jira.spring.io/browse/AMQP-712
=> Upgrade RabbitMQ Java Client to 4.1.0

spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/BrokerRunning.java
- Improve Javadocs
- Fail fast when broker required and don't log the full stack trace
=> Polish BrokerRunning @Rule

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java
JIRA: https://jira.spring.io/browse/AMQP-714
Reduce log noise by suppressing `null` properties.
=> AMQP-714: Improve MessageProperties.toString()

build.gradle
JIRA: https://jira.spring.io/browse/AMQP-719
=> AMQP-719: upgrade to Logback 1.1.11

build.gradle
JIRA: https://jira.spring.io/browse/AMQP-727
SLF4J Errors now that amqp-client uses it.
=> AMQP-728: Fix Logging Dependencies

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AutoRecoverConnectionNotCurrentlyOpenException.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-723
Improve Javadocs; recommend resetting autoRecoveryEnabled.
=> AMQP-723: Improve Javadocs for Recovery Exceptions

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
JIRA: https://jira.spring.io/browse/AMQP-740
Also some SONAR false positives.
=> AMQP-740: Fix Ack Synchronization

README.md
This change fixes the header section, formatting the header in bold and fixing the icon resource.
=> Fix the header section of the readme

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java
JIRA: https://jira.spring.io/browse/AMQP-756
=> AMQP-756: Add support for no-local consumers

build.gradle
JIRA: https://jira.spring.io/browse/AMQP-769
=> AMQP-769: Add Manifest Info Including Module Names

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-774
Resolves https://github.com/spring-projects/spring-amqp/issues/669
=> AMQP-774: Add autoStartup to @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ErrorHandlerTests.java
JIRA: https://jira.spring.io/browse/AMQP-794
In the `ConditionalRejectingErrorHandleri.DefaultExceptionStrategy`,
if the `cause` of the `ListenerExecutionFailedException` is a `MessagingException`,
traverse the `cause` tree to find the root cause of all such exceptions unless
it's a fatal cause itself (`MethodArgumentResolutionException` or `MessageConversionException`).
The final fatal check is performed on the root cause.
=> AMQP-794: CRErrorHandler: Traverse cause tree

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
JIRA: https://jira.spring.io/browse/AMQP-793
Throw an exception to the caller when attempting to ack/nack a
message on a closed channel.
=> AMQP-793: Exception on ack for closed Channel

build.gradle, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/LongRunningIntegrationTestCondition.java, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/RabbitAvailableCondition.java
- eliminate the `platform-commons` dependency
- make the `jupiter-api` dependency optional
=> Fix JUnit dependencies

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Hello, Gary and Artem
Please take a look at several small improvements to rabbit template.
You can find explanation for each change in commit messages.
Happy to resolve any comments if you find this PR useful.
=> Improve rabbit template

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MultiMethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-799
Support the designation of a single `@RabbitHandler` as the default if there is no
match.
=> AMQP-799: Add default @RabbitHandler support

src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-799
=> AMQP-799: Default @RabbitHandler Docs

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/719
Add `replyPostProcessor` to the container factory.
=> GH-719: Container Factory: Add replyPostProcessor

src/reference/asciidoc/amqp.adoc
=> Fix code format errors

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java
[Jira](https://jira.spring.io/browse/AMQP-805)
[Issue](https://github.com/spring-projects/spring-amqp/issues/722)
=> Made AmqpAppender.postProcessMessageBeforeSend  protected

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessagePropertiesTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/730
**Cherry-pick to 2.0.x and 1.7.x**
=> GH-730: Fix NPE in the MessageProperties

build.gradle, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt, spring-rabbit/src/test/kotlin/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt
Given the perceived increase in Kotlin users, perhaps we should consider adding some test cases.
=> [For Team Consideration/Discussion] Add Kotlin test case

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerLongTests.java
JIRA: https://jira.spring.io/browse/AMQP-810
SMLC: adjusting the `concurrentConsumers` did not consider `maxConcurrentConsumers`.
- increase added consumers even if at max
- decrease removed consumers when they had increased due to max being set
Further, decreasing the `maxConcurrentConsumers` did not remove consumers if there
were more consumers than the new max.
- don't add consumers beyond the max
- don't remove consumers unless the new max is exceeded
**cherry-pick to 2.0.x, 1.7.x**
There will be some minor conflicts in 1.7.x since the modified test is JUnit5.
=> AMQP-810: Fix adjust consumers when max present

spring-amqp/src/main/java/org/springframework/amqp/core/MessageDeliveryMode.java
=> Polish MessageDeliveryMode JavaDoc

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java
JIRA: https://jira.spring.io/browse/AMQP-814
Add retry to avoid race conditions with auto-delete, exclusive queues.
**back port to 1.7.x, without lambda in RabbitAdmin**
=> AMQP-814: Add retry to RabbitAdmin

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
- add delivery tag to inbound delivery logs
- add trace logging to channel method calls
**cherry-pick to 2.0.x, 1.7.x**
=> Add more debug/trace logging

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/Delivery.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitBindingIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BrokerDeclaredQueueNameTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/UnackedRawIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-820
Use a discrete `InternalConsumer` for each queue.
=> AMQP-820: SMLC: Remove InternalConsumer decorator

spring-amqp/src/main/java/org/springframework/amqp/core/ExchangeBuilder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/Exchange.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/Queue.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/QueueBinding.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AbstractRabbitAnnotationDrivenTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/annotation-driven-sample-config.xml
JIRA: https://jira.spring.io/browse/AMQP-822
Add `declare` and `admins` properties.
=> AMQP-822: @RabbitListener: `@QueueBinding` enhance

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/kotlin/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt
JIRA: https://jira.spring.io/browse/AMQP-823
Allow resolution to a bean instance or bean name.
=> AMQP-823: @RabbitListener errorHandler

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BrokerEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BrokerEventListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BrokerEventListenerTests.java
JIRA: https://jira.spring.io/browse/AMQP-826
=> AMQP-826: Fix package tangle

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/support/SendRetryContextAccessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-825
__cherry-pick to 2.0.x__
=> AMQP-825: Add Reply RetryTemplate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
JIRA: https://jira.spring.io/browse/AMQP-829
If the channel closes while we are waiting for a reply, throw an
exception instead of waiting to time out.
=> AMQP-829: RabbitTemplate Req/Resp Fail Fast

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-830
Tested with a stand-alone boot app.
=> AMQP-830 Enable Hostname Verification by default

src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-600
=> Remove references to obsolete 'x-ha-policy'

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryCachingConnectionIntegrationTests.java
Avoid duplicate initialization.
=> Set initialized in initialize()

spring-amqp/src/main/java/org/springframework/amqp/core/AnonymousQueue.java, spring-amqp/src/main/java/org/springframework/amqp/core/Queue.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-834
Resolves https://github.com/spring-projects/spring-amqp/issues/818
Locate anonymous (auto-delete, exclusive) queues on the local node.
=> AMQP-834: AnonymousQueue: Master Locator

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java
Fixes https://github.com/spring-projects/spring-amqp/issues/824
**cherry-pick to 2.0.x*
=> GH-824: Fix Log4j2Appender with headers exchange

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/RabbitNamespaceUtils.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.1.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerParserTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ListenerContainerParserTests-context.xml
Fixes https://github.com/spring-projects/spring-amqp/issues/794
* Expose an `after-receive-post-processors` in the
`<rabbit:listener-container>` component
* Upgrade to the latest dependencies
=> GH-794: add after-receive-post-processors for XML

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/833
Allow setting any properties not directly exposed by the factory.
=> GH-833: Add container configurer callback

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-840
=> AMQP-840: RabbitTemplate add hook for timeouts

spring-amqp/src/main/java/org/springframework/amqp/support/converter/MessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/MessagingMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/RemoteInvocationAwareMessageConverterAdapter.java
Incorrectly added to message converter.
=> Remove erroneous @Nullable

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, src/reference/asciidoc/quick-tour.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/861
=> GH-861: Quick Tour Docs Polishing

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultClassMapper.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
* Some code style refactoring: mostly lambdas to method references
=> Use Context CL whenever it is applicable

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpAdmin.java, spring-amqp/src/main/java/org/springframework/amqp/core/AmqpTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/ChannelCallback.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
=> Add missing `@Nullable`

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java
First iteration on major smells.
=> Sonar fixes

src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/879
=> GH-879: Doc @RabbitListener with Message

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/transaction/RabbitTransactionManager.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/transaction/RabbitTransactionManagerIntegrationTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/883
=> GH-883: Fix regression in transaction manager

spring-amqp/src/main/java/org/springframework/amqp/core/MessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, src/reference/asciidoc/amqp.adoc
- add warning log if the container is not configured for MANUAL acks
- improve docs
=> @RabbitListener async result polishing

spring-amqp/src/main/java/org/springframework/amqp/utils/JavaUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/DirectRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java
- proposed new model for non-null property propagation
=> Reduce factory method complexity

spring-amqp/src/main/java/org/springframework/amqp/support/SimpleAmqpHeaderMapper.java, spring-amqp/src/main/java/org/springframework/amqp/utils/JavaUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
- also fix race in `RabbitTemplateTests`
=> More JavaUtils - hasText and BiConsumer Flavors

spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/RabbitListenerTestHarness.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/905
=> GH-905: Configurable executor on @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/InvocationResult.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/910
__cherry-pick to 2.1__
=> GH-910: Fix return type headers for async returns

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/910
Further to the previous patch, avoid async return type erasure by using
the actual generic type of the async result, unless it is a wildcard type.
If it's a wildcard, fall back to the actual return object's type.
=> GH-910: Fix async return type erasure

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessagePropertiesTests.java
Related issue: https://github.com/spring-projects/spring-amqp/issues/918
=> GH-918 Handle null correlationId

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/933
=> GH-933: Fix NPE in PublisherCallbackChannelImpl

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java
https://stackoverflow.com/questions/55630983/spring-amqp-compatibility-with-ibm-jvm/55633883#55633883
=> Configurable Key/Trust Store Algorithm

spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/repeatable/AbstractRabbitAnnotationDrivenTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerEndpointTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerMultipleQueueIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpointTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistrarTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
Also avoid `access()` method in `RabbitTemplatePublisherCallbacksIntegrationTests3`.
=> Use assertThatThrownBy() Vs. ExpectedException

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
See https://github.com/spring-projects/spring-amqp/issues/994
Move the `closingLatch.countDown()` to `waitForConfirmsOrDie()` so we
are sure the in-flight async close is running.
Previously, there was a race because the latch was counted down just
before the close was issued on the async thread.
=> GH-994: Improve test

src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/appendix.adoc, src/reference/asciidoc/logging.adoc, src/reference/asciidoc/sample-apps.adoc
I only fixed some small typo errors.
=> (docs): fixed small errors

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java
If a listener method completes its async result with a null
value, do not attempt to send the result.
=> Handle async result with null completion

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, src/reference/asciidoc/si-amqp.adoc
* Upgrade to the latest dependencies, including Checkstyle
* Fix new Checkstyle violations
* Fix typo in the `si-amqp.adoc`
=> Add nohttp Gradle plugin

spring-amqp/src/main/java/org/springframework/amqp/core/ExchangeBuilder.java, spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/FixedReplyQueueDeadLetterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
- also add type parameter to the exchange `build()` method
=> Add well-known arguments to Queue/Exchange Builder

spring-rabbit/src/main/resources/META-INF/spring.schemas
Related to https://github.com/spring-projects/spring-integration/issues/2987
**Cherry-pick to 2.1.x, 2.0.x & 1.7.x**
=> Add HTTPS entries for XSD into spring.schemas

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/log4j2/AmqpAppenderTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/logback/AmqpAppenderTests.java, spring-rabbit/src/test/resources/log4j2-amqp-appender.xml, spring-rabbit/src/test/resources/logback-test.xml, src/reference/asciidoc/logging.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1049
=> GH-1049: Support SaslConfig in logging appenders

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1062
**cherry-pick to 2.1.x, 2.0.x**
=> GH-1062: Fix missing queues log message

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1067
=> GH-1067: Fix deprecated setters

spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/LogLevels.java, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/LogLevelsCondition.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePerformanceIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryRepeatIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/test/RepeatProcessor.java
- add lifecycle to `@LogLevels` to avoid adjusting the log on each iteration
- with `@RepeatableTest` there is a template context between the class and method contexts
=> Convert repeated tests to JUnit 5 @RepeatableTest

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AdminParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.2.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/AdminParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/AdminParserTests-2-context.xml, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1074
Cherry-pick to 2.1.x
=> GH-1074: Admin explicitDeclarationsOnly Property

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ConsumerBatchingTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1101
=> GH-1101: Message Listener Micrometer Timers

src/reference/asciidoc/whats-new.adoc
Simply missing an `r` in `appenders`
=> Fixed small smelling mistake

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java
=> Ignore AlreadyClosedException in SimpleConnection

spring-amqp/src/main/java/org/springframework/amqp/core/AbstractDeclarable.java, spring-amqp/src/main/java/org/springframework/amqp/core/AbstractExchange.java, spring-amqp/src/main/java/org/springframework/amqp/core/Binding.java, spring-amqp/src/main/java/org/springframework/amqp/core/Declarable.java, spring-amqp/src/main/java/org/springframework/amqp/core/DeclarableCustomizer.java, spring-amqp/src/main/java/org/springframework/amqp/core/Queue.java, spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessorTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/FixedReplyQueueDeadLetterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1125
- pull up the common `arguments` field to `AbstractDeclarable`
- add `x-single-active-consumer` as a first class `QueueBuilder` argumemt
=> GH-1125: Add DeclarableCustomizer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatefulRetryOperationsInterceptorFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatelessRetryOperationsInterceptorFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/MessageBatchRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1127
=> GH-1127: Add MessageBatchRecoverer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessorTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1138
=> GH-1138: Support @Repeatable user annotations

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessageTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1152
=> GH-1152: Use contentEncoding in Message.toString()

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1148
Fix is now in Spring Framework.
=> GH-1148: Revert Log4j Appender Change

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1148
Fix is now in Spring Framework.
=> GH-1148: Revert Log4j Appender Change [2.1.x]

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/ReplyPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
- allow customization of the reply message based on the request message.
=> Add @RabbitListener replyPostProcessor

src/reference/asciidoc/amqp.adoc
@artembilan I wrote software to do it so it probably doesn't need much review. Maybe just build locally and give the table a quick scan.
=> Sort container attributes table alphabetically

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1181
=> GH-1181: Fix memory leak with user correlation

build.gradle
Upgrade to the latest versions of both asciidoctor and asciidoctorPdf,
to avoid further technical debt.
=> Upgrade to latest Asciidoctor versions

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/Connection.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitAccessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/RabbitExceptionTranslator.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA https://jira.spring.io/browse/AMQP-608
Initial Commit
=> AMQP-608: Add new connection factories

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1198
=> GH-1198: Support AddressResolver

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AbstractRabbitAnnotationDrivenTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1208
Also polish code for setting consumer arguments.
=> GH-1208: Allow SpEL in all @RabbitListener Props

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1211
=> GH-1211: Add OAUTH2 Support to RabbitCFactoryBean

spring-amqp/src/main/java/org/springframework/amqp/support/converter/MessagingMessageConverter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitReturnTypesTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1220
=> GH-1220: Add replyContentType to @RabbitListener

spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/RabbitListenerProxyTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyAndCaptureTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyTest.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ClientRecoveryCompatibilityTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SingleConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateHeaderTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ListenFromAutoDeleteQueueTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, src/checkstyle/checkstyle.xml
Mixture of plain and BDD Mockito, sometimes in the same class.
Enforce with checkstyle.
=> Consistent Use of BDDMockito

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpMessageReturnedException.java, spring-amqp/src/main/java/org/springframework/amqp/core/ReturnedMessage.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannel.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java, src/reference/asciidoc/amqp.adoc
- a single parameter instead of 5
=> Simplify ReturnCallback for Lambdas

spring-amqp/src/main/java/org/springframework/amqp/support/AmqpHeaders.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CorrelationData.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitOperations.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/MessagingTemplateConfirmsTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplateTests.java
In preparation for https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/303
=> Add CorrelationData spring-messaging header

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1237
**cherry-pick to 2.2.x, 2.1.x, 1.7.x**
=> GH-1237: RCFB Close key/trust store input streams

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1249
Add protected getters for private fields; add `handleDiscarded()`.
=> GH-1429: Improve ConditionalRejectingErrorHandler

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1258#issuecomment-711670729
**I will backport to 2.2.x with a no-op default**
=> GH-1258: Add OOMHandler to the listener containers

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactoryTests.java
The new connection factories did not honor `RabbitUtils.isPhysicalCloseRequired()`.
=> New Conn. Factories - Honor Physical Close Request

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1268
=> GH-1268: New Factories: Call ConnectionListener(s)

src/reference/asciidoc/amqp.adoc
=> Fix Spelling errors

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapterTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1285
=> GH-1285: Fix @RabbitListener with @Headers

spring-amqp/src/main/java/org/springframework/amqp/core/MessagePostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1267
=> GH-1267: Overloaded MPP Method with Exchange/RK

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessageTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1313
=> GH-1313: Add Message CTOR with default Props

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CompositeConnectionListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ConnnectionListenerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1315
=> GH-1315: Add onFailed() to ConnectionListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/RabbitNamespaceUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerMockTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ListenerContainerParserTests-context.xml, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1318
=> GH-1318: Support the Global Flag in basicQos

spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/DelegatingDecompressingPostProcessor.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1320
=> GH-1320: AlwaysDecompress true in DelegatingDecomp

spring-amqp/src/main/java/org/springframework/amqp/core/AnonymousQueue.java, spring-amqp/src/main/java/org/springframework/amqp/core/Queue.java, spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/FixedReplyQueueDeadLetterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/TransactionalEventListenerTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1325
=> GH-1325: Queue API Deprecations and Improvements

src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1329
=> GH-1329: Document Multi-Threaded Strict Ordering

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RejectAndDontRequeueRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/MissingIdRetryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1335
Allow customization of exception message.
=> GH-1335: RejectAndDontRequeueRecoverer Improvement

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1351
=> GH-1351: Add MessageProperties for Argument Match

build.gradle, settings.gradle, spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/StreamRabbitListenerContainerFactory.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamMessageListener.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamMessageProperties.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/adapter/StreamMessageListenerAdapter.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/converter/DefaultStreamMessageConverter.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/converter/StreamMessageConverter.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/AbstractIntegrationTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, spring-rabbit-stream/src/test/resources/log4j2-test.xml, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/BaseRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MultiMethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/api/ChannelAwareMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/MessageListenerTestContainer.java
See https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/
Basic `@RabbitListener` support.
Required a higher level abstraction for listener container factories.
=> GH-1352 RabbitMQ Stream Support - Initial Commit

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AfterCompletionFailedException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1362
**cherry-pick to 2.3.x**
=> GH-1362: Enable Capture of Tx Synchronization Fail

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/ConsumerCustomizer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/ProducerCustomizer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamOperations.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/StreamSendException.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/package-info.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/StreamMessageProperties.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/converter/DefaultStreamMessageConverter.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/package-info.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/AbstractIntegrationTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java
See https://github.com/spring-projects/spring-amqp/issues/1352
Initial commit of Stream Producer support.
=> GH-1352: Add RabbitStreamTemplate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1365
=> GH-1365: Recover Manual Declarations

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/index.adoc, src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1352
=> GH-1352: Docs for RabbitMQ Stream Plugin Support

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ContainerAdminTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1370
=> GH-1370: Containers: Find Admin in Parent Context

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessageTests.java
=> Do not deserialize in Message.toString()

spring-amqp/src/main/java/org/springframework/amqp/remoting/client/AmqpClientInterceptor.java, spring-amqp/src/main/java/org/springframework/amqp/remoting/client/AmqpProxyFactoryBean.java, spring-amqp/src/main/java/org/springframework/amqp/remoting/service/AmqpInvokerServiceExporter.java, spring-amqp/src/test/java/org/springframework/amqp/remoting/RemotingTest.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1383
=> GH-1383: Deprecate Remoting

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1099
=> GH-1099: Fix Javadocs for Publisher Connection

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/EnableRabbit.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1397
=> GH-1397: Typo in @EnableRabbit class description

spring-amqp/src/main/java/org/springframework/amqp/core/Declarables.java, spring-amqp/src/test/java/org/springframework/amqp/core/DeclarablesTest.java, spring-amqp/src/test/java/org/springframework/amqp/core/DeclarablesTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1396
Make constructor more flexible by upper bounded wildcard
=> GH-1396: Declarables constructor is too strict

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
Fix https://github.com/spring-projects/spring-amqp/issues/1402
=> GH-1402: SMLC: Fix BlockingQueueConsumer#queue init

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1463
=> GH-1463: RabbitTemplate.logReceived() Protected

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
See https://github.com/spring-projects/spring-amqp/issues/1474
(Does not resolve because 2 issues are reported there).
`BatchingStrategy` was not set by container factory.
=> GH-1474: Fix BatchingStrategy Propagation

spring-amqp/src/main/java/org/springframework/amqp/core/AsyncAmqpTemplate2.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate2.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CorrelationData.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererWithConfirms.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate2Tests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ComplexTypeJsonIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/MessagingTemplateConfirmsTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests2.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateRoutingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/AsyncReplyToTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1473
Given the stability of the project, it was simplest to copy the `AsyncRabbitTemplate`
rather than adding a lot of conditional code.
**2.4.x only; I will submit a separate PR for main**
=> GH-1473: Switch to CompletableFuture

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamOperations2.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate2.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, src/reference/asciidoc/stream.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1480
=> GH-1480: Switch to CompletableFuture in s-r-stream

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1484
=> GH-1484: RabbitListener.batch() Override

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/OptionalPayloadTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1491
=> GH-1491: Support Optional/null Payloads

build.gradle
to get the new look and feel and the new features.
=> Switch to spring-asciidoctor-backends

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/SuperStream.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/SuperStreamSACTests.java
To support spring-cloud-stream.
=> GH-1465: Add Routing Key Strategy to SuperStream

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/SuperStreamConcurrentSACTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/support/AbstractIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1509
=> GH-1509: Add Concurrency for Super Streams

build.gradle, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/BrokerRunningSupport.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RestTemplateHolder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RestTemplateNodeLocator.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/WebFluxNodeLocator.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactoryIntegrationTests.java, src/reference/asciidoc/amqp.adoc
- also remove hard dependency on `spring-webflux` from `spring-rabbit-junit`.
=> GH-1419: Add RestTemplateNodeLocator

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatefulRetryOperationsInterceptorFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ClosingRecoveryListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistrar.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/support/ContainerUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/RabbitExceptionTranslator.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1514
=> GH-1514: Pattern-Matched instanceof Where Possible

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/BaseRabbitListenerContainerFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1425
=> GH-1425: Configure ReplyPostProcessor via Factory

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1382
Add expressions; make private method protected.
=> GH-1382: Republish Recoverer Improvements

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/FactoryFinder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/NodeLocator.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RestTemplateNodeLocator.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/WebFluxNodeLocator.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/NodeLocatorTests.java
Between `LocalizedQueueConnectionFactory` and `NodeLocator` implementations.
=> Fix Class Tangle

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java
JIRA: https://jira.spring.io/projects/AMQP/issues/AMQP-52
Differences with AMQP 1.0 types - AMQP 1.0 is not supported.
=> AMQP-52:Remove Obsolete MessageProperties Comments

src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/appendix.adoc, src/reference/asciidoc/stream.adoc, src/reference/asciidoc/testing.adoc
Fixes some small typos in documentation
=> Fix typos in documentation

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1560
Use address resolution hierarchy to determine destination host(s).
=> GH-1560: Caching CF toString() Improvements

src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2445
=> GH-2445: Doc Stream Provisioning and Dependency

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/kotlin/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2461
=> GH-2461: RabbitListenerErrorHandler with Async

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/StreamAdmin.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2451
=> GH-2451: Add StreamAdmin

src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2473
=> GH-2473: Clarify Choosing a Connection Factory

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2490
=> GH-2490: Add forceStop to Container Factories

.github/release-files-spec.json
Resolves https://github.com/spring-projects/spring-amqp/issues/2493
=> GH-2493: Sync Gradle .module File to Maven

build.gradle
Do not reference the full project dir.
=> Fix Micrometer Docs Generation

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BrokerDeclaredQueueNameTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2504
=> GH-2504: Add SmartLifecycle to Conn. Factories

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java
Addendum to #2504 - when the connection is reset, the `channelsExecutor` is shut down. It needs to be reset so that a new one is created, if necessary.
=> GH-2504: Clear Deffered Channel Close Executor

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/utils/SerializationUtils.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/AllowedListDeserializingMessageConverterTests.java, src/reference/asciidoc/amqp.adoc
**cherry-pick to 3.0.x, 2.4.x**
No back port issues needed.
=> Change Defaults

src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2546
Incorrectly added prototype scope to the bean (copy/paste from test).
=> GH-2546: Fix Super Stream Example in Docs

src/api/overview.html, src/reference/antora/modules/ROOT/pages/amqp/broker-configuration.adoc, src/reference/antora/modules/ROOT/pages/amqp/connections.adoc, src/reference/antora/modules/ROOT/pages/amqp/listener-queues.adoc, src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/async-annotation-driven/enable.adoc, src/reference/antora/modules/ROOT/pages/amqp/request-reply.adoc, src/reference/antora/modules/ROOT/pages/amqp/sending-messages.adoc
=> Changed some broken links

src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/micrometer-observation.adoc, src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/micrometer.adoc
=> docs: add a warning for batch listeners and observation

spring-amqp/src/main/java/org/springframework/amqp/core/Declarables.java
=> Restrict `getDeclarablesByType()` to Declarable

src/reference/antora/modules/ROOT/pages/amqp/abstractions.adoc
I think asterisk character is missing in the black rounded part. That why I create this PR. Please check again and tell me if I miss something.
Reference AMQP Docs
https://docs.spring.io/spring-amqp/reference/amqp/abstractions.html#message
=> Escape Asterisk

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java
Closes https://github.com/spring-projects/spring-amqp/issues/2815
=> RabbitAdmin change behavior redeclare

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java
I think we can reduce `else if` condition in method `convertLongStringIfNecessary`
=> Improve condition for `convertLongStringIfNecessary` from `DefaultMessagePropertiesConverter`

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/micrometer/RabbitListenerObservation.java
=> Remove deprecated `ListenerLowCardinalityTags.DELIVERY_TAG`

antora-playbook.yml
=> Update javadoc-extension and UI version

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/micrometer/TracingTests.java
=> Add observationConvention Setter for RabbitStreamTemplate
