spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-463
JRockit throws an `IllegalArgumentException` if a
`TreeMap$Entry` is used after removal via the `Iterator`.
The `PublishSubscribeChannelImpl` uses this technique.
Obtain the entry value before removing the entry.
Add a test to reproduce the problem with the JRockit JVM.
Currently sends 10k messages across 100 threads; also tested
with 1m messages across 100 threads with no lost confirms.
=> AMQP-463: Fix Publisher Confirms with JRockit

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-463
JRockit throws an `IllegalArgumentException` if a
`TreeMap$Entry` is used after removal via the `Iterator`.
The `PublishSubscribeChannelImpl` uses this technique.
Obtain the entry value before removing the entry.
Add a test to reproduce the problem with the JRockit JVM.
Currently sends 10k messages across 100 threads; also tested
with 1m messages across 100 threads with no lost confirms.
Conflicts:
spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
Resolved.
=> [BackPort] AMQP-463: Fix Publisher Confirms with JRockit

spring-amqp/src/main/java/org/springframework/amqp/core/Address.java, spring-amqp/src/main/java/org/springframework/amqp/core/AddressUtils.java, spring-amqp/src/test/java/org/springframework/amqp/core/AddressTests.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-466
1.4.1 introduced direct reply to and reply to address decoding required
using `AddressUtils`. The code should have been put in the `Address` ctor.
=> AMQP-466: Move Direct reply-to Decoding to Address

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/resources/logback-test.xml
JIRA: https://jira.spring.io/browse/AMQP-474
When logs are generated soon after initialization (as is the case for
the test cases), some log messages could (infrequently) be lost.
This is due to the `EventSender` seeing a `null` `applicationId`, generating
a routing key:
[null.org.springframework.amqp.rabbit.logback.AmqpAppenderIntegrationTests.DEBUG]
instead of:
[AmqpAppenderTest.org.springframework.amqp.rabbit.logback.AmqpAppenderIntegrationTests.DEBUG]
(in the case of the logback test case).
Since this does not match a binding, the log message is discarded and the test fails.
Since the `applicationId` setter is called before `start()`, on the same thread, the
only way this can happen is if the `EventSender` runs on a CPU that has a stale
copy of the `AmqpAppender` in its cache (the …
=> AMQP-474: Fix Log Appenders

src/reference/asciidoc/quick-tour.adoc
Enable attribute substitution in the code blocks, per http://asciidoctor.org/docs/user-manual/#applying-substitutions
=> AMQP-486: Fix Version in QuickStart

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-467
Log at INFO level when a new connection is established; useful
when recovering a connection after a broker loss.
=> AMQP-467: INFO Log When Connection is Opened

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MultiMethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java
JIRA: https://jira.spring.io/browse/AMQP-444
Move `DelegatingInvocableHandler` to the `adapter` package to avoid
backwards reference from `HandlerAdapter` to `listener` package.
=> AMQP-444: Fix Package Tangle

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerLongTests.java
JIRA: https://jira.spring.io/browse/AMQP-498
In earlier versions, the while loop to drain the queue took an early exit
when the channel was transacted. (This was actually incorrect since message
delivery is not transactional, only acks).
AMQP-388 introduced a new OR condition on the loop: `consumer.hasDelivery()`.
This effectively made the `continuable` boolean in the OR condition irrelevant.
This boolean was true if messages were received and the channel was not transactional.
Another side effect was the `continuable` boolean was incorrectly used to adjust the consumers
if the workload demanded. Instead, that decision should have depended just on whether
messages were received; whether the channel is transacted is irrelevent.
Remove the `continuable` boolean; fix the while loop and use a …
=> AMQP-498: Adjust Consumers With ChannelTransacted

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java
JIRA: https://jira.spring.io/browse/AMQP-500
Enable algorithm selection when not using certificates.
__cherry-pick to 1.4.x__
=> AMQP-500: Configurable SSL Algo, No Properties

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
JIRA:https://jira.spring.io/browse/AMQP-506
`RabbitTemplate` provides a method `getUnconfirmed` to get aged
non-confirmed correlation data.
This was not thread-safe.
While the `pendingConfirms` objects in `RabbitTemplate` and `PublisherCallbackChannelImpl`
are concurrent hash maps, they are maps of maps with the inner maps being
`Collections.synchronizedSortedMap`. While iterating over these maps, they must be
synchronized.
Add a test case to reproduce the exception and verify the problem is resolved.
__cherry-pick to 1.4.x, 1.3.x__
=> AMQP-506: Publisher Confirms Concurrency

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-499
The previous fix was incomplete. The listener container also
emits a WARN log when the queue cannot be consumed due to exclusivity.
Provide a mechanism to customize that log too.
=> AMQP-499: Make WARN Log Configurable

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/RabbitExceptionTranslator.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-511
Previously, only literals were supported in `@SendTo` values.
Add support for SpEL expressions (`#{...}`).
=> AMQP-511: Support SpEL in @SendTo

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-516
Previously, anonymous queues (no value attribute) were only declared
auto-delete and exclusive if those attributes were not provided.
Still default to true, but also use the value if provided.
=> AMQP-516: Fix Auto-Declare Anonymous Queue

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-522
Update docs.
__cherry-pick to 4.1.x (minus docs)__
=> AMQP-522: Make RabbitAdmin Constants Public

build.gradle
- amqp-client: 3.5.4
- http-client: 1.0.0.RELEASE
- http-client is no longer optional - needed by the LQCF
- exclude it's spring-web dep and use one consistent with others
- spring framework 4.1.7
=> Update SF, rabbit amqp and http Client Versions

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
JIRA: https://jira.spring.io/browse/AMQP-524
Enable mocking of a connection factory that supports publisher confirms and
returns callbacks.
=> AMQP-524: Publisher CF Extract Interface

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-540
Previously, class-level `@RabbitListener` was not detected if the class was proxied.
This solves the reported problem but it is incomplete - see AMQP-541.
=> AMQP-540: Fix @RabbitHandler on Proxy

spring-amqp/src/main/java/org/springframework/amqp/core/Binding.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/ZipPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistrar.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java
- remove redundant modifiers
- overridable methods called from ctors
=> Code Polishing (Sonar)

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java
The symptom looks like:
```
2015-12-11 05:13:01,513 ERROR SimpleAsyncTaskExecutor-1 [org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer] - <Consumer thread error, thread abort.>
java.lang.AssertionError
at org.mockito.internal.stubbing.InvocationContainerImpl.setMethodForStubbing(InvocationContainerImpl.java:108)
at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:54)
at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
at org.mockito.internal.creation.cglib.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:59)
at org.apache.commons.logging.impl.Log4JLogger$$EnhancerByMockitoWithCGLIB$$8fedbd5a.trace(< …
```
=> Fix some race conditions around mocks

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
JIRA: https://jira.spring.io/browse/AMQP-556
If a listener doesn't shut down within the timeout, when it
next checks whether it is active, it gets an NPE.
Since it is a terminating listener, it is benign.
=> AMQP-556: NPE in SMLC After Shutdown Timeout

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-564
Nacks for pending confirms were not generated if the connection was
detected as closed in logicalClose.
__cherry-pick to master - new tests and comment in CCF__
=> AMQP-564: Fix Confirm Callback Nacks

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-568
Fix `DataInputStream` mapping - return the `LongString` by default.
=> AMQP-568: Long LongString Header Handling

spring-amqp/src/main/java/org/springframework/amqp/support/converter/ContentTypeDelegatingMessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/ContentTypeDelegatingMessageConverterTests.java
JIRA: https://jira.spring.io/browse/AMQP-547
In the `ContentTypeDelegatingMessageConverter` deprecate the methods with typos and introduce new.
=> AMQP-547 Fix typo in ContTypeDelegatingMC methods

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpointTests.java
JIRA: https://jira.spring.io/browse/AMQP-582
Since the recent change in the SF-4.3 the `MessageMethodArgumentResolver` supports now the payload conversion option.
With that the conversion exception expectation has been changed.
Make `MethodRabbitListenerEndpointTests` compatible with SF-4.3, as well retain compatibility with previous versions.
=> AMQP-582: Compatibility with SF-4.3

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-591
Permits are not released after a connection loss.
Cached channels held a reference to the old connection proxy; since this
was the key to the checkoutPermits map, the map entry was not found
when closing, and hence the permits were not increased.
The solution is to change the channel proxy to be permanent, and just refresh
its target connection; remove the hashCode method so cached channels can always
find their permits. Previously the hashcode included the hashcode of the delegate.
For `CacheMode.CONNECTION`, when a new proxy is created it is permanently stored
in `allocatedConnections` (previously called `openConnections`). When a connection
is retrieved from the cache, if the underlying physical connection is closed we
look at the next …
=> AMQP-591: Channel Cache (with Permits) Backport

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java
JIRA: https://jira.spring.io/browse/AMQP-598
When looking for `Collection<Declarable>` using `getBeansOfType()` ignore
prototype/scoped beans and do not initialize FBs.
__cherry-pick to 1.5.x__
=> AMQP-598: Admin: Ignore Scoped and Prototype Beans

src/reference/asciidoc/amqp.adoc
http://stackoverflow.com/questions/37164725/how-to-gracefully-close-channel-and-connetion-when-queue-length-reach-zero/37168185#37168185
Don't stop the container on the consumer thread.
Also remove some left-over test code from the event listener example.
=> Doc Improvement

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
https://build.spring.io/browse/AMQP-MEIGHT-711
The `RabbitTemplateIntegrationTests.testSymmetricalReceiveAndReply()` use `this.template.receive()` which is based on the `receiveTimeout`.
Since `receiveTimeout == 0` by default that means "receive-no-wait".
and there is no guaranty that the message appears in the queue exactly after the previous `receiveAndReply()`.
The existing `this.template.setReplyTimeout(10000);`in the test does not make effect for the `receive()` operations.
* Specify `this.template.setReceiveTimeout(10000);` to meet test requirements and have some time window to wait for the message in the queue.
=> RabbitTemplateIntegrationTests: fix timing issue

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java
JIRA: https://jira.spring.io/browse/AMQP-648
The `cancelled` boolean is set when there are no more consumers in `handleCancelOk`.
Consider a case where a container is configured for multiple queues; one queue is deleted
from the broker. In `handleCancel`, we attempt to cancel the rest of the consumers so the
container can recover.
However, if those cancels fail (e.g. if the broker goes down), we'll never finalize the
consumer.
Move the consumer removal (and setting `cancelled`) to `basicCancel` instead. We don't really
care whether or not we get the `cancelOk`s.
Add mock test - also tested with the SI sample modified for 2 queues
- set a breakpoint in `handleCancel`
- delete a queue
- stop/start rabbitmq
- release the breakpoint
- container recovers
__backport to 1.6.x__
=> AMQP-648: Fix Race in handleCancel (SMLC)

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-656
`@Argument(name = "x-dead-letter-exchange", value = "")`
Should pass an empty string to RabbitMQ indicating the default exchange, instead of `null`.
Change the BPP to detect this arguments and support adding other arguments using the
`spring.rabbitmq.emptyStringArguments` property.
__cherry-pick to 1.6.x - but fix up the diamond operator in the BPP__
=> AMQP-656: Support Empty Strings in Arguments

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ActiveObjectCounter.java
There is no need to pass timeout as object Long here, looks like a typo.
=> chore: primitive long in ActiveObjectCounter.await()

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/ConsumeOkNotReceivedException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
https://build.spring.io/browse/AMQP-SONAR-1671/
With a receive timeout of only 1ms, we might not get a consumeOk.
=> Fix Test Race Condition

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
In preparation for JIRA: https://jira.spring.io/browse/AMQP-675
=> Allow RabbitTemplate Subclasses to Access Replies

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java
Fixes https://jira.spring.io/browse/AMQP-680
=> AMQP-680: Avoid allocations from Method.getParameterTypes() in MessagingMessageListenerAdapter

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java
https://sonar.spring.io/component_issues?id=org.springframework.amqp%3Aspring-amqp-dist%3Amaster#resolved=false|types=BUG
Checking wrong connection object to attach recovery listener.
After merge, needs backport of this default listener.
=> Fix Sonar Detected Bad instanceof Check

spring-amqp/src/main/java/org/springframework/amqp/AmqpApplicationContextClosedException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryLifecycleTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerTests.java
JIRA: https://jira.spring.io/browse/AMQP-682
Stop the container if the connection factory has been destroyed by Spring.
This can happen if a non-Spring-managed container uses a Spring-managed connection factory.
=> AMQP-682: DMLC: Fatal Connection Error

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerTests.java
https://build.spring.io/browse/AMQP-MEIGHT-919
The `AmqpApplicationContextClosedException` is considered as fatal for the `DirectMessageListenerContainer` but only in case of direct `getConnectionFactory().createConnection()`.
All subsequent interactions with `connection` and its `channels` may lead to the same problem because `ConnectionFactory` may be closed in between
* Catch `AmqpApplicationContextClosedException` in the general `doConsumeFromQueue()` block and rethrow it as a `AmqpConnectException` to fail container fast.
* Rework `DirectMessageListenerContainerTests.testNonManagedContainerDoesntStartWhenConnectionFactoryDestroyed()` to let pass the first `getConnectionFactory().createConnection()`, but fail on the other subsequent interactions with `connection` and its `channels` as …
=> Fix AmqpAppCtxClosedE race condition in the DMLC

spring-amqp/src/main/java/org/springframework/amqp/ImmediateAcknowledgeAmqpException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/transaction/ListenerFailedRuleBasedTransactionAttribute.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/LocallyTransactedTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-687
When using a rule-based transaction attribute with a rollback/no-rollback rule,
the rule is ignored when providing the transaction attribute directly to the container
rather than via a transaction advice,
Also, user exceptions are always wrapped in a `ListenerExecutionFailedException` which
limits the ability to configure rules, even when using an advice.
- Honor the attribute `rollBackOn()` mechanism within the container
- Add `ListenerFailedRuleBasedTransactionAttribute` to allow the user to configure rules based on the actual exception.
Add docs.
AMQP-686: Handle ImmediateAcknowledgeAmqpException
JIRA: https://jira.spring.io/browse/AMQP-686
Previously, `ImmediateAcknowledgeAmqpException` only worked if thrown by
an error handler, not a …
=> AMQP-687: Fix Conditional Rollback [1.7.x]

spring-amqp/src/main/java/org/springframework/amqp/core/ExchangeBuilder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-695
JIRA: https://jira.spring.io/browse/AMQP-696
Also make `ExhangeBuilder` ctor public to enable building by type name (e.g. from a boot property).
__cherry-pick to 1.7.x, 1.6.x__
=> AMQP-696: RabbitManagementTemplate Fix

spring-amqp/src/main/java/org/springframework/amqp/core/CorrelationAwareMessagePostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/core/MessagePostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/Correlation.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/CorrelationData.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-697
Add support for modifying publisher confirms `CorrelationData` during message post processing.
Change `AsyncRabbitTemplate` to use a stateless MPP, move all state to the `CorrelationData`.
__master only - I will issue a new 1.x backport PR after review/merge__
=> AMQP-697: CorrelationAwareMessagePostProcessor

spring-amqp/src/main/java/org/springframework/amqp/core/CorrelationAwareMessagePostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/Correlation.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/CorrelationData.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-697
Add support for modifying publisher confirms `CorrelationData` during message post processing.
Change `AsyncRabbitTemplate` to use a stateless MPP, move all state to the `CorrelationData`.
Conflicts:
spring-amqp/src/main/java/org/springframework/amqp/core/MessagePostProcessor.java
spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java
spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java
spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
Resolved.
=> AMQP-697: CorrelationAwareMessagePostProcessor [1.7.x]

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-708
When publisher confirms or returns are enabled, and a container is stopped
while the broker is down, an auto-recover channel is leaked. It is later
recovered by the client library but has no code actually consuming from it.
While the channel is flagged to physically close it (to prevent the client
from recovering it), that close is avoided because `isOpen()` returns false
until the connection/channel is recovered.
Unconditionaly close the channel if physical closure is required.
Add a test with mocks; also tested with the SI sample and a real broker.
Before the patch, observe the leaked consumer on the admin console.
After the patch, the consumer is no longer retained after recovery.
Also, ignore `AlreadyClosedException` s in `RabbitUtils`. …
=> AMQP-708: Fix Leaked AutoRecovered Channel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitResourceHolder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtilsTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-711
Previously, messsages were unconditionally requeued when an external
transaction manager is used; this was not consistent with local
transactions, where the normal requeue logic was honored.
Fix the case when the transaction manager is a RabbitTransactionManager
When the transaction manager is a `RabbitTransactionManager`, the resource is already bound and
the resource bound within the transaction template execute() method is ignored.
The `requeueOnRollback` field needs to be set in the correct resource holder.
Change the `ConnectionFactoryUtils.bindResourceToTransaction` method to return the actual
resource holder that is bound to the transaction and set the boolean therein.
Polishing - clear the transaction thread locals.
Handle corner case …
=> AMQP-711: Make Transaction Rollback Consistent [1.7.x Backport]

spring-amqp/src/main/java/org/springframework/amqp/core/ExchangeBuilder.java
JIRA: https://jira.spring.io/browse/AMQP-716
The builder was not consistent with the Abstract class regarding
the default for the `durable` flag.
I will issue a separate PR for master after merge - it will need `what's new`, and code changes including tests.
=> AMQP-716: ExchangeBuilder and Durable

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-718
Don't refresh the underlying channel if a transaction is in process.
__cherry-pick to 1.7.x, 1.6.x__
=> AMQP-718: Fix Channel Close During Transaction

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/resources/logback-test.xml, src/reference/asciidoc/logging.adoc
JIRA: https://jira.spring.io/browse/AMQP-715
To avoid an overhead via fulfilling StackTrace add `includeCallerData` to the `AmqpAppender` with `false` by default
**Cherry-pick to 1.7.x**
=> AMQP-715: Logback AmqpAppender.includeCallerData

CONTRIBUTING.adoc
https://jira.springsource.org/browse/AMQP seems unavailable for now. Changed it to spring.io domain.
=> Update JIRA link in contributing guide.

src/reference/asciidoc/testing.adoc
Obvious Fix
`@AfterClass` method has to be static or else Exception is thrown.
=> Fix tearDown method in testing.adoc code example

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
The access to this field is synchronized in other places, only missing here.
=> Synchronize access to DMLC.consumers in scheduled task

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerLongTests.java
JIRA: https://jira.spring.io/browse/AMQP-725
Lower the log level to DEBUG when a consumer cancellation is expected, such as during shutdown or changing queues.
__cherry-pick to 1.7.x__.
=> AMQP-725: Suppress WARN Log for Normal Cancel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
JIRA: https://jira.spring.io/browse/AMQP-737
Don't attempt to `basicCancel()` a consumer if the channel is already closed.
Also, catch `IllegalStateException` which can occur if the application context is already closed.
__cherry-pick to 1.6.x, master (change to multi-catch on master)__
=> AMQP-737: SMLC: Fix Consumer Cancel Stack Trace

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java
- Add the connection factory's object identity hash code to the connection id String
- Add the connection id to the "Created new Connection" log
__cherry-pick to master__
=> Add Object Hash to Connection Id

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/DirectRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-736
Support concurrency on the annotation to avoid having to configure a different factory for each listener.
=> AMQP-736: @RabbitListener.concurrency

spring-amqp/src/main/java/org/springframework/amqp/support/converter/SimpleMessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/SimpleMessageConverterTests.java
JIRA: https://jira.spring.io/browse/AMQP-739
Reject non-convertible source objects rather than sending a `null` body.
=> AMQP-739: SimpleMessageConverter + Not Convertible

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/log4j2/AmqpAppenderTests.java, spring-rabbit/src/test/resources/log4j2-amqp-appender.xml
JIRA: https://jira.spring.io/browse/AMQP-743
The `AmqpManager` isn't registered as a lifecycle in the `LoggerContext`,
therefore the `AmqpAppender` should take care about its lifecycle.
* Override `stop()` method for the `AmqpAppender` and perform
`AmqpManager.stop()` from there
* Fix `AmqpAppenderTests` for cross-platform assertions
* Add `status="DEBUG"` to the `log4j2-amqp-appender.xml` to track
the logging configuration process
**Cherry-pick to 1.7.x & 1.6.x**
=> AMQP-743: Properly stop Log4J2 AmqpAppender

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ContainerShutDownTests.java
https://build.spring.io/browse/AMQP-MEIGHT-JOB1-1125/test/case/251270844
It is possible the template's channel is returned to the cache before the container starts.
In that case, the container gets that channel and there's only one insted of two.
Also add a consumer started event to the DMLC, which was missing.
=> Fix Race in ContainerShutDownTests

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
It is now possible to configure `afterReceivePostProcessors` on `AbstractRabbitListenerContainerFactory`, which in turn will delegate this to `RabbitListenerContainer#setAfterReceivePostProcessors`.
See further conversation [AMQP-753](https://jira.spring.io/browse/AMQP-753)
=> AMQP-753 Adds possibility to set MessagePostProcessors

README.md
The provided link about AMQP protocol is to the official AMQP web site which is for AMQP 1.0 spec. This commit fixes it, providing the link to the RabbitMQ AMQP 0.9.1 spec supported by this component.
=> Updated AMQP reference to 0.9.1 spec

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java
"Queue with name that starts with 'amq.' cannot be declared." logged unconditionally.
__Cherry-pick to 1.6.x, 1.7.x__
=> Remove Bogus DEBUG log.

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-764
Fixes https://github.com/spring-projects/spring-amqp/issues/651
Previously, `stopped` was set in `stop()` after the context was closed.
This was done to prevent inadvertent re-opening of the connection which
would prevent the application from terminating.
This was too early since other beans destroyed before the factory might
need to send messages.
Remove `Smartlifecycle` and move setting `stopped` to `destroy()`, but
still only after the context is closed; since `destroy()` can be called
by users to reset the connection (although `resetConnection()` is now the
preferred way to do that.
=> AMQP-764: Move Setting stopped to destroy()

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-765
When confirms/returns are enabled we defer the close; suppress
the logged exception if a normal `ShutdownSignalException` is thrown.
=> AMQP-765: Suppress Exception on Deferred Close

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-765
When confirms/returns are enabled we defer the close; suppress
the logged exception if a normal `ShutdownSignalException` is thrown.
Conflicts:
spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java
Resolved.
=> AMQP-765: Suppress Exception on Deferred Close [Backport]

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
Can we lower the log level from DEBUG to TRACE in nextMessage()? There are too many these kind of messages.
=> too many debug logs in nextMessage

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/WhiteListDeserializingMessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessageTests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-766
Add white list for classes/packages that can be deserialized in Message.toString().
__cherry-pick to 1.7.x, 1.6.x, 1.5.x__
=> AMQP-766: Deserialization in Message.toString()

src/reference/asciidoc/amqp.adoc
See just above here: https://docs.spring.io/spring-amqp/docs/1.7.4.RELEASE/reference/html/_reference.html#_exchange
Block terminator uses - instead of =.
Also add a note about PP and SpEL.
=> Fix NOTE Block; Clarify @RabbitListener Config

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/MissingIdRetryTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/index-docinfo.xml, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-748
The prefetch default value used to be 1, which could lead to
under-utilization of efficient consumers. The default prefetch value
is now 250, which should keep consumers busy in most
common scenarios and thus improve throughput.
=> AMQP-748: Increase default prefetch for SimpleListenerContainer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/LocallyTransactedTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-772
If an `afterReceivePostProcessor` in the listener container configuration
returns `null`, discard the message.
=> AMQP-772: Container MPP - Discard Message

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplateTests.java
Fixes spring-projects/spring-amqp#671
The `RabbitManagementTemplate.deleteExchange(Exchange)` delegates
to the `client.deleteQueue()`
* Fix `RabbitManagementTemplate.deleteExchange(Exchange)` to properly
delegate to the `client.deleteExchange()`
**Cherry-pick to 1.7.x, 1.6.x & 1.5.x**
=> GH-671: Fix RabbitManagementTemplate.delExchange

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Fixes spring-projects/spring-amqp#672
The `StandardBeanExpressionResolver` is based on the
`TemplateAwareExpressionParser` which can parse any string to the
`LiteralExpression` or to the `CompositeStringExpression` if
template tokens (`#{` & `}`) are present in the source expression.
This way we don't need to deal with literal concatenations within
templated expression.
The expression like `#{'foo.' + myBean.bar}` can be replaced
with the `foo.#{myBean.bar}`
=> GH-672: Fix SpEL parsing for @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java
The `this.taskScheduler` reset is done outside of the
`if (this.running) {` block causing NPE on the second `stop()` call
**Cherry-pick to 1.7.x & 1.6.x**
=> Fix `AsyncRabbitTemplate.stop()` for NPE

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
In many complex environments e.g. boot properties, cloud connectors, environment overrides etc.
it can be difficult to debug connection problems.
Add INFO logs with configured broker address(es) before connecting.
=> Log Connection Attempts

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-779
Allow the use of a user-supplied correlationId instead of one
generated by the `RabbitTemplate`.
It is the user's responsibility to ensure uniqueness.
__The backport to 1.7.x will need some work because of the `String` Vs. `byte[]`
correlationId changes__
=> AMQP-779: User correlationId with reply container

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-780
Log an error if a consumer doesn't start within the timeout; make the timeout configurable.
This can happen if the task executor doesn't have enough threads to support the concurrency.
=> AMQP-780: Configurable consumer start timeout

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultClassMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/ContentTypeDelegatingMessageConverterTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java, spring-amqp/src/test/resources/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests-context.xml
JIRA: https://jira.spring.io/browse/AMQP-768
This is mostly backport of AMQP-747
Since `Jackson2JsonMessageConverter` has a `setJavaTypeMapper()`
there is no reason to overhead this maintenance version with extra ctors
=> [1.5.x] AMQP-768: Add trustedPackages to deserialization

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-784
When looking for matching methods, we matched on no annotation or @Payload.
Match should have been no annotation(s) or not @Header.
=> AMQP-784: Fix multi method @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConsumeOkEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/quick-tour.adoc
JIRA: https://jira.spring.io/browse/AMQP-776
JIRA: https://jira.spring.io/browse/AMQP-777
JIRA: https://jira.spring.io/browse/AMQP-782
Publish an event when a consumer successfully consumes from a queue.
Publish an event when an SMLC listener throws an `Error`.
Doc polishing.
Update minimum client version in docs; remove reference to broker version
since that's no longer linked to the client.
__cherry-pick to 1.7.x (minus DMLC change)__
=> AMQP-776: More Consumer Events

build.gradle, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ActiveObjectCounter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java
JIRA: https://jira.spring.io/browse/AMQP-785
Fixes: spring-projects/spring-amqp#689
- Only stop the container on one thread
- Ignore concurrent stops
- Interrupt consumer threads that are attempting to declare queues
- In `restart()` don't start a new consumer if the container is stopping
- Defer publishing consumer failure events until container is stopped
- Add a RecoveryListener if needed to ensure channels are never recovered
- Fix event publishing for `Error` - it is fatal
__backport to 1.7.x will require work__
Clear the declaring flag when exiting `start()` with exception.
Release the `activeObjectCounter` when interrupted while declaring.
Polishing stopped container lifecycle
Since restarted consumer is not be aware about stopped container,
it can restart properly when RabbitMQ …
=> AMQP-785: SMLC Lifecycle fixes [17x Back port]

spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/BrokerRunning.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateMPPIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-790
Previously, `afterReceivePostProcessors` were not called on `sendAndReceive()`
operations.
=> AMQP-790: Fix after receive MPPs with send/receive

spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryCachingConnectionIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/listener/ListenFromAutoDeleteQueueTests-context.xml
- Reduce container `receiveTimeout` so containers stop faster
- Remove unnecessary `Thread.sleep()`s
Reduced runtime from 5'26'' to 3'11'' on my machine.
=> Improve Test Run Times

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/703
When we adjust consumers down by more than 1 instance we end up with the
`IndexOutOfBoundsException` because we perform removal by the
calculated index.
* Change algorithm to remove only from `0` index.
In the end it doesn't matter which consumers remain in the container
=> GH-703: DLC.adjustConsumers: Fix remove algorithm

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
JIRA: https://jira.spring.io/browse/AMQP-796
If an admin uses a transactional `RabbitTemplate` it will start a transaction.
If the connection was opened due to a `RabbitTemplate` operation it should participate
in the same transaction.
Previously, the template used a second channel and treated it as a local transaction.
Also fix the `RabbitAdmin` so it does no work if there is nothing to declare.
=> AMQP-796: Fix Admin Transaction

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java
JIRA: https://jira.spring.io/browse/AMQP-800
The `LocalizedQueueConnectionFactory` incorrectly destroyed the injected default
connection factory. It should only destroy factories that it creates.
**cherry-pick to 1.7.x**
=> AMQP-800: LocalizedQueueConnectionFactory Fix

build.gradle, gradle/wrapper/gradle-wrapper.properties
- add support for JUnit5 tests
- resume gradle testing of JUnit5 tests - `RabbitTemplateMPPIntegrationTests.java`, `SimpleMessageListenerContainerLongTests.java`
=> Upgrade to Gradle 4.6

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
JIRA: https://jira.spring.io/browse/AMQP-801
The proper place to emit the `ConsumeOkEvent` is really a
`handleConsumeOk()` callback when broker answers us that consumer has
been subscribed to the queue
**Cherry-pick to 1.7.x**
=> AMQP-801: Move ConsumeOkEvent to handleConsumeOk

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, src/reference/asciidoc/amqp.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/734
Add `declareCollections` flag to admin (default false).
__cherry-pick to 2.0.x, 1.7.x__
=> GH-734: Option to suppress declaring Collections

spring-amqp/src/main/java/org/springframework/amqp/AmqpResourceNotAvailableException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java, src/reference/asciidoc/amqp.adoc
Fixes spring-projects/spring-amqp#723
To avoid an `NPE` when connection returns `null` for the
`createChannel()` in case of `channelMax` is reached, throw newly
introduced `AmqpResourceNotAvailableException`.
This exception can be used in the `RetryPolicy` to retry the original
operation after some back-off - the channel permit may be released in
between
**Cherry-pick to 2.0.x and 1.7.x**
=> GH-723: Add AmqpResourceNotAvailableException

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
This reverts commit ca09dfa6d264b04ade3fba09109574374207ea5f.
Add important note to the docs about `RabbitAdmin` and exclusive queues.
=> Revert previous commit

build.gradle, spring-amqp/src/test/java/org/springframework/amqp/support/SimpleAmqpHeaderMapperTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AbstractRabbitAnnotationDrivenTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerMultipleQueueIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/logback/AmqpAppenderConfiguration.java
- update jaCoCo version
- new `Integer(n)` is deprecated
- @PreDestroy no longer present
- SSL change
=> Changes to build with JDK10

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java
JIRA: https://jira.spring.io/browse/AMQP-817
Previously, synthetic nacks were processed on the client thread, which caused
a deadlock if the user attempted some operation such as creating a new channel
on that thread.
Also, when generated from a application-level `close()` a similar deadlock between
the connection factory and `PublisherCallbackChannelImpl` could occur.
Synthetic nacks are now always processed on a separate thread.
=> AMQP-817: Synthetic NACKs on separate thread

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-818
`errorHandler` and `returnExceptions` properties were not injected into class-level listeners.
=> AMQP-818: Fix Class-level listener properties

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/Connection.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-821
Since headers are not fragmented, limit the stack trace header length to
prevent failures.
=> AMQP-821: Repub Recoverer limit stack trace header

spring-amqp/src/main/java/org/springframework/amqp/core/Declarables.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-808
Deprecate the use of `Collection<Declarable>` in favor of a dedicated
`Declarables` container object to avoid unexpected side-effects when
getting all `Collection` beans from the application context.
=> AMQP-808: Add Declarables for declaring collection

build.gradle
Fixes https://github.com/spring-projects/spring-amqp/issues/736
The latest `hop` makes most of its dependencies as `optional` to meet
a reactive/non-reactive environment requirements
=> GH-736: Upgrade to RabbitMQ hop-2.1

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/core/AmqpManagementOperations.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitManagementTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitRestApiTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/appendix.adoc, src/reference/asciidoc/whats-new.adoc
JIRA: https://jira.spring.io/browse/AMQP-812
=> AMQP-812: Deprecate RabbitManagementTemplate

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultClassMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/MarshallingMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/package-info.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/DefaultClassMapperTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2XmlMessageConverterTests.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/package-info.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/package-info.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/package-info.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/package-info.java
Packages with `@Nullable` annotations need to have `@NonNulApi` at the package level.
There may be classes in these packages that have nullable arguments/returns that are
not currently marked as `@nullable`. These will be fixed over time. Some fixes are
included here.
=> Add @NonNullApi where appropriate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
JIRA: https://jira.spring.io/browse/AMQP-827
Use the correct `payloadConverter` in the `MessagingMessageConverter`
to support `@RabbitListener` `Message<?>` return types.
**cherry-pick to 2.0.x, 1.7.x**
=> AMQP-827: Fix @RL reply Message<?> conversion

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java
Resolves https://github.com/spring-projects/spring-amqp/issues/796
Support removal of containers from the registry.
=> GH-796: RLEndpointRegistry - unregister

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
JIRA: https://jira.spring.io/browse/AMQP-828
When a channel is closed normally (e.g. due to a timeout), the shutdown listener
completed the future with the `ShutdownSignalException`.
2018-08-28 05:09:18,261 ERROR org.springframework.amqp.rabbit.core.RabbitTemplate [Test worker] : Consumer failed to receive message: TemplateConsumer [channel=Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://guest@127.0.0.1:5672/,1), conn: Proxy@39754e71 Shared Rabbit Connection: SimpleConnection@1a81c806 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 59780], consumerTag=null]
com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
This preempts the …
=> AMQP-828: No Exception on normal close

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java
JIRA: https://jira.spring.io/browse/AMQP-11
`@ManagedOperation` s on `RabbitAdmin` had no descriptions.
Further, `RabbitAdmin` was not a `@ManagedResource`.
Note: Certain admin operations are not available remotely, e.g. over RMI
since they involve non-`Serializable` objects.
Also fix async `purgeQueue` operation to actually use the `noWait` argument.
=> AMQP-11: Add descriptions to @ManagedOperations

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/777
Disable declaring collections by default now that `Declarables` is supported.
This is so that Boot 2.1 apps will not have issues without additional configuration
of the `RabbitAdmin`.
=> GH-777: declareCollections to false by default

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryIntegrationTests.java
When a connection is auto-recovered, the `RabbitAdmin` is not
invoked to re-declare auto-delete queues because the connection
listeners are not invoked.
Close an auto-recovered connection before it is recovered.
Tested with a stand-alone spring-cloud-bus application.
**Cherry-pick to 2.0.x, 1.7.x**
=> Close auto-recovering connection

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/resources/log4j2-amqp-appender.xml, spring-rabbit/src/test/resources/logback-test.xml
Resolves https://github.com/spring-projects/spring-amqp/issues/829
Allow setting the RabbitMQ connection name in the log appenders.
=> GH-829: Add connection name to log apenders

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpoint.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpoint.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/MessageListenerTestContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
JIRA: https://jira.spring.io/browse/AMQP-838
The `setMessageConverter()` on the listener container was only used
to convey the converter from the container factory to the listener
adapter. This is confusing to users hand-wiring a container since
there is an implication it is used by the container itself.
Deprecate the method, and use the endpoint (by default) to convey
the converter to the endpoint's adapter.
=> AMQP-838: Deprecate container.setMessageConverter

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerMockTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/837
- Skip recovery of consumers who's queue has been deleted during recovery
- If recovery is aborted (no connection) reset `consumersToRestart`
=> GH-837: Fix DMLC Recovery with queue removal

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerPlaceholderParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerMockTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/841
=> GH-841: Close executor in the PublisherConChannel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java
Fixes https://github.com/spring-projects/spring-amqp/issues/846
Send and receive with a direct container (the default) fails on the second
operation because the remplate is not registered as a listener with the
callback channel.
`doSendAndReceiveWithDirect` does not invoke `doSendAndReceiveAsListener`
within `execute` because the channel is obtained from the container.
The first send and receive succeeds because `execute` is invoked once in the
`useDirectReplyTo` which determines whether the broker supports direct
reply-to.
`addListener()` is called from `execute()` after a channel has been received
from the cache.
Fix is to call `addListener()` from `doSendAndReceiveWithDirect`.
=> GH-846: Fix send and receive with confirms

src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-845
**cherry-pick to 2.0.x** but change the second sentence to
Also, the `RabbitConnectionFactoryBean` will call `enableHostnameVerification()` if you set the `enableHostnameVerification` property to `true`; this will be the default in version 2.1.
=> AMQP-845: SSL Doc Polishing

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java
JIRA: https://jira.spring.io/browse/AMQP-846
=> AMQP-846: Fix NPE (adviceChain)

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateDirectReplyToContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, src/reference/asciidoc/amqp.adoc
JIRA: https://jira.spring.io/browse/AMQP-848
When using a `DirectReplyToMessageListenerContainer` the consumer was released
for reuse after a normal `onMessage` or if an exception is thrown.
Neither of these occur when the reply times out.
Move the release to a `finally` block - it is idempotent so won't affect the
normal `onMessage` case.
=> AMQP-848: RT with DRTMLC - always release consumer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/DirectRabbitListenerContainerFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java
This capability is being added primarily to support configuration of these values when using Spring Boot application.properties/yml.When using code based configuration an alternate method is to use the setContainerConfigurer callback.
Resolves #893
=> Allow messagesPerAck and ackTimeout to be configurable when using DirectRabbitListenerContainerFactory

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java
https://build.spring.io/browse/AMQP-SONAR-2481/
With a short timeout, the consumer might not receive the `consumeOk` in time.
```
org.springframework.amqp.rabbit.core.ConsumeOkNotReceivedException: Blocking receive, consumer failed to consume: TemplateConsumer [channel=Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://guest@127.0.0.1:5672/,1), conn: Proxy@374f01d1 Shared Rabbit Connection: SimpleConnection@b347172 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 60288], consumerTag=amq.ctag-Ss7YrnvpFtQfF00vlzQ1qQ]
at org.springframework.amqp.rabbit.core.RabbitTemplate.createConsumer(RabbitTemplate.java:2584)
at org.springframework.amqp.rabbit.core.RabbitTemplate.consumeDelivery(RabbitTemplate.java:1341)
at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$re …
```
=> Fix race in test

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/905
Default container thread names are based on the bean name. `@RabbitListener`
containers are not beans; use `getListenerId()` instead (which falls back
to bean name for other containers).
**cherry-pick to all supported branches**
=> GH-905: Fix @RabbitListener Thread Names

build.gradle, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/TestRabbitTemplate.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/ExampleRabbitListenerCaptureTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/TestRabbitTemplateTests.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitBootstrapConfiguration.java
Fixes https://github.com/spring-projects/spring-amqp/issues/914
* Rework `RabbitBootstrapConfiguration` into the `ImportBeanDefinitionRegistrar`
and check for bean definitions presence it is going to register.
This way an override from the `RabbitListenerTestBootstrap` is going to
have a precedence and its `RabbitListenerTestHarness` won't allow a
regular `RabbitListenerAnnotationBeanPostProcessor` to be registered
* Rework `TestRabbitTemplate` to gather all the listener container
from the `ContextRefreshedEvent` instead of the `SmartInitializingSingleton`.
Looks like Spring doesn't care about their order, therefore we need to
be sure that `RabbitListenerAnnotationBeanPostProcessor` has populated
its `registry` with containers before.
* Demonstrate that `allowBeanDefinitionOverriding = …
=> GH-914: Honor AllowBeanDefOverriding = false

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java
For https://github.com/spring-projects/spring-integration/issues/2797
We need to access the `getUnconfirmed()` method but might as well expose
the entire template in case other situations arise.
=> Add getter for RabbitTemplate on AsyncTemplate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/LazyContainerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BrokerDeclaredQueueNameTests.java, src/reference/asciidoc/amqp.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/923
While checking for missing or mis-matched queues, a lazily-loaded
listener container can deadlock for 60 seconds.
This occurs if the `allBeanNamesByType` cache does not currently have
an entry for `Queue` (e.g. cleared by registering a singleton).
When lazy beans are referenced, the `RabbitListenerEndpointRegistry`
starts the container and `start()` waits for the consumers to start.
Getting a reference to the lazy bean holds the `singletonObjects`
lock, which is required by the consumer(s) to get the `Queue` beans
to check.
Add a test case to demonstrate the issue.
Disable the redeclaration logic during the initial start of such a
container.
=> GH-923: Fix start delay for @Lazy @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Currently a `byte[]` gets converted to a String using an
`ArrayToStringConverter`, which is not very useful because
you get a list of numbers representing the bytes.
Add a `BytesToStringConverter`.
=> Add BytesToStringConverter

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/935
- Don't call basicCancel if already canceled
- Catch all `Exception`s
**cherry-pick to all supported** (may need a separate PR, especially for 1.7.x)
=> GH-935: Handle all exceptions in handleDelivery

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/935
- Don't call basicCancel if already canceled
- Catch all `Exception`s
=> GH-935: Handle all exceptions in handleDelivery [2.0.x]

CODE_OF_CONDUCT.adoc, CONTRIBUTING.adoc, README.md, spring-amqp/src/main/java/org/springframework/amqp/remoting/client/AmqpClientInterceptor.java, spring-amqp/src/main/java/org/springframework/amqp/remoting/service/AmqpInvokerServiceExporter.java, spring-rabbit-junit/src/test/java/org/springframework/amqp/rabbit/junit/BrokerRunningTests.java, spring-rabbit/README.adoc, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.2.xsd, src/api/overview.html, src/dist/README.md, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/further-reading.adoc, src/reference/asciidoc/preface.adoc, src/reference/asciidoc/quick-tour.adoc, src/reference/asciidoc/sample-apps.adoc, src/reference/asciidoc/si-amqp.adoc
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://baz:15672/api/ ([https](https://baz:15672/api/) result UnknownHostException).
https://foo/bar ([https](https://foo/bar) result UnknownHostException).
https://host1:15672 ([https](https://host1:15672) result UnknownHostException).
https://host2:15672 ([https](https://host2:15672) result UnknownHostException).
https://host:port ([https](https://host:port) result UnknownHostException).
These URLs were switched to …
=> URL Cleanup

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpAdmin.java, spring-amqp/src/main/java/org/springframework/amqp/core/QueueInformation.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java
Retain (don't deprecate) the current method for JMX users.
=> Add type-safe queue properties to AmqpAdmin

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java
Fixes https://github.com/spring-projects/spring-amqp/issues/967
=> GH-967: Use `ChannelProxy` CL instead of context

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/logback/AmqpAppenderTests.java, src/reference/asciidoc/logging.adoc, src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/970
* Some code polishing and internal refactoring for `AmqpAppender`
=> GH-970: Add `AmqpAppender.verifyHostname` option

spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/RabbitListenerTestHarness.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/ExampleRabbitListenerSpyTest.java
Fixes https://github.com/spring-projects/spring-amqp/issues/973
When we use `@EnableRabbit` and `@RabbitListenerTest` in the same
configuration set, e.g. mixing real `@Configuration` and test one for
`@RabbitListenerTest`, we may end up with the case when `@EnableRabbit`
is processed before `@RabbitListenerTest`, so, `RabbitListenerTestHarness`
bean is not going to appear in the application context.
* Override `getOrder()` for the `RabbitListenerTestHarness` to give it
higher priority than regular `RabbitListenerAnnotationBeanPostProcessor`,
so it is registered first and then the last one won't override existing
bean
=> GH-973: Higher order for RabbitListenerTestHarness

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/Jackson2JavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/ProjectingMessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Add support for converting JSON message bodies to Spring Data Projection interfaces.
This allows very selective, and low-coupled bindings to data, including
the lookup of values from multiple places inside the JSON document.
For example the following interface can be defined as a message payload type:
```
interface SomeSample {
@JsonPath({ "$.username", "$.user.name" })
String getUsername();
}
```
Accessor methods will be used to lookup the property name as field in the
received JSON document by default.
The @JsonPath expression allows customization of the value lookup, and even
to define multiple JSONPath expressions, to lookup values from multiple
places until an expression returns an actual value.
=> Add Spring Data projection support

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/994
`CCF.destroy()` abruptly shuts down the `channelsExecutor` (if present).
This can cause `RejectedExecutionException` because the publisher
callback channel uses the same executor to schedule nacks if necessary.
- Use an `ActiveObjectCounter` to keep track of in-flight async closes
- Wait until there are not active objects before calling `shutDown()` (instead of `shutDownNow()`)
- Wait until all queued tasks are complete
- Add `PublisherCallbackChannelFactory` to make testing possible
__cherry-pick to 2.1.x__
**Suggest reviewing with `?w=1`**
=> Fix RejectedExecutionException during close

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/main/java/org/springframework/amqp/support/AmqpHeaders.java, spring-amqp/src/main/java/org/springframework/amqp/support/SimpleAmqpHeaderMapper.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/batch/SimpleBatchingStrategy.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
When debatching a batched message and the listener handles them
one-at-a-time, it may be helpful to know when the last message in
the batch is being processed.
=> Add isLastInBatch to MessageProperties

spring-amqp/src/main/java/org/springframework/amqp/support/AmqpHeaders.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/batch/SimpleBatchingStrategy.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Useful, for example, in a Spring Integration aggregator release
strategy.
=> Add amqp_batchSize message header

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/999
Logical and physical closure of `PublisherConfirmChannel`s is deferred
until the acks have been received.
When using a fixed cache, via `channelCheckoutTimeout`, the permits
must not be released until the channel is actually returned to the cache
(logical) or closed (physical).
**backport will be required after merge due to refactoring**
=> Fix ChannelCheckoutTimeout with PublisherConfirms

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/999
The previous commit fixes permit releases when the close is deferred
waiting for confirms.
For logical closes, the `releasePermitIfNecessary()` was moved to
`returnToCache`. However, if `logicalClose()` detects the underlying
channel is already closed, it is not returned to the cache, it is
discarded.
In this case, `logicalClose()` must release the permit.
Add a test case to expose the issue and verify it's corrected.
=> GH-999: Release permit when channel is closed

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapterTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1009
The `MessageListenerAdapter` build an `InvocationResult` without
a return type info leading to the NPE in the
`AbstractAdaptableMessageListener` when we try to parse a generic
argument for the returned `Mono` or `ListenableFuture`
* Fix a potential NPE in the `AbstractAdaptableMessageListener.asyncSuccess()`
* Add `MessageListenerAdapterTests.testListenableFutureReturn()` to ensure
that `channel.basicAck()` is called from the `MessageListenerAdapter`
as well
=> GH-1009: Fix NPE in the AbsAdaptMessageListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapterTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1006
When listener method returns `Mono<Void>`, the `success` callback is
not called from the Reactor because there is no value to handle.
* Move `basicAck()` to the `completeConsumer` which is called when `Mono`
is completed successfully with value or without
=> GH-1006: Fix listener ack for `Mono<Void>`

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1012
Make the channel available in `RabbitListenerErrorHander` for when
MANUAL ack mode is being used.
=> Add AmqpHeaders.CHANNEL in error hander

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java
The `DirectMessageListenerContainer` did not publish a listener
failed event for a connection failure.
**cherry-pick to all 2.x branches**
=> DMLC: Publish event for connection failure

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
https://github.com/spring-projects/spring-amqp/issues/1021
Sending the result from a `RabbitListenerErrorHandler` was broken
for class-level `@RabbitListener` because the send to expression
was lost.
=> GH-1021: Fix `@SendTo` after error is handled

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/ActiveObjectCounter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitBindingIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/support/ActiveObjectCounterTests.java
- tangle between `connection` and `listener` since `ActiveObjectCounter`
is now used in `CachingConnectionFactory`
- move `ActiveObjectCounter` from `listener` to `support`
=> Fix new package tangle

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1026
When using a `channelCheckoutTimeout` with `CacheModeConnection`,
we incorrectly spin waiting for a connection until the timeout
expires.
We should only wait for a connection if the limit is exceeded.
**cherry-pick to all supported**
=> GH-1026: Fix Delay with CacheMode.CONNECTION

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.2.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1029
Add `shuffleAddresses` to the `CachingConnectionFactory`.
=> GH-1029: Add option to randomize connection order

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BrokerEventListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/RabbitListenerEndpointRegistry.java
* Also remove redundant `stop(Runnable)` implementations which repeat
a `default` one in the `SmartLifecycle`
**Cherry-pick to 2.1.x & 2.0.x**
=> Fix `SmartLifecycle.stop(Runnable)` usage

spring-amqp/src/main/java/org/springframework/amqp/core/BatchMessageListener.java, spring-amqp/src/main/java/org/springframework/amqp/core/MessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/api/ChannelAwareBatchMessagelistener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/api/ChannelAwareMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerManualAckIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerRecoveryRepeatIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerTxSizeIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerWithRabbitMQ.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1032
- Needs (a lot) more tests
- Needs support in `@RabbirtListener`
=> GH-1032: Add consumer-side batching support

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1038
Don't set `evaluatedFastReplyTo` if we didn't actually evaluate it because
the broker is down on the first request.
**cherry-pick to all 2.x; backport to 1.7.x**
=> GH-1038: RT: Fix evaluatedFastReplyTo

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1034
The monitor task now cancels the consumer after a failed ack/nack,
whether or not the channel `isOpen()` returns true.
Test with a mock channel that stays open after a failed ack.
**cherry-pick to 2.1.x, 2.0.x**
=> GH-1034: DMLC: Cancel consumer after failed ack

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/BatchMessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/ListenerExecutionFailedException.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ConsumerBatchingTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/MessageHandlerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1032
Add basic consumer batching support to the `@RabbitListener` infrastructure.
**Still needs more tests** But I think this can be merged after review.
=> GH-1032: Consumer Batching Phase 2 @RabbitListener

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerMockTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1034
If the connection factory refreshed the target connection, the DMLC
is not made aware of it and so we never consume from the new channel.
**cherry-pick to all 2.x**
=> GH-1034: DMLC: Detect target channel changed

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1038
The previous fix to catch `AmqpConnectException` was incorrect - the
`ShutdownSignalException` for the passive queue declaration failure
is wrapped in an `AmqpConnectException` so we would have failed to
detect the failure.
Also, it has been reported that sometimes an `AmqpIOException` is thrown.
- Add `AmqpIOException` to the catch block
- Search for, and explitly check for the queue declaration failed exception
- For all other cases rethrow so we can test again
=> GH-1038: RT: More evaluateFastReplyTo Fixes

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2XmlMessageConverterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
For the JSON and XML converters, assume the content type is supported
if missing or default.
Add option to revert to previous behavior.
=> AbstractJackson2MessageConv.: assume supported CT

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
When a BlockingQueueConsumer fails to passively declare a queue, it is supposed to sleep for `failedDeclarationRetryInterval` milliseconds before retrying.  However the `Thread.sleep` is wrapped inside an `if(logger.isWarnEnabled())` with the effect that, when WARN-level logging is _not_ enabled for this class then it ignores the retry interval and tries again immediately - potentially hundreds of times per second.
This is not caught by the tests, because when the tests are running the root logger is set to INFO.
Fix is to move the sleep outside the logger `if` block.
=> Setting for BlockingQueueConsumer.failedDeclarationRetryInterval ignored if logging not enabled

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ContainerUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ContainerUtilsTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1053
`ContainerUtils.shouldRequeue` did not traverse the cause tree so we never
matched on this exception.
=> Fix ImmediateRequeueAmqpException

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1055
Prevent deadlocks in the amqp-client.
The reason the existing test didn't catch this is because the nested
send was performed on a different template/connection.
=> GH-1055: Invoke Conf/Return callbacks on executor

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/appendix.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/1058
The listener adapter did not honor the exception types used to
complete the async result and always requeued.
=> GH-1058: Fix Reject/Requeue for Async Returns

.travis.yml, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/1058
The listener adapter did not honor the exception types used to
complete the async result and always requeued.
=> GH-1058: Fix Reject/Requeue for Async Returns [BackPort]

build.gradle, spring-rabbit/src/test/resources/logback-test.xml
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/grussell/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.12.0/7f44f5201f79d6f7010a1515699a5f6c40e49cb/log4j-slf4j-impl-2.12.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/grussell/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```
Use the logback binding for the amqp client.
=> Remove log4j-slf4j-impl test dependency

spring-amqp/src/main/java/org/springframework/amqp/AmqpRejectAndDontRequeueException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ContainerUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/1065
Previously, messages with fatal errors (e.g. conversion) would be
left in an un-acked state.
They are now rejected and NOT requeued by default.
=> GH-1065: Reject fatal with MANUAL ack mode

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit-2.2.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests2.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/SimplePublisherConfirmsTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1067
=> GH-1067: Add enum for publisher confirm type

publish-maven.gradle
Since the dependendency management Gradle plugin is applied and the
Jackson BOM is used, versions for this artifact are resolved by the
plugin.
The plugin configuration in this build disables POM customization, as
otherwise it would add `<dependendencyManagement>` sections in the
generated POMs.
This commit adds a missing script in the 2.1.x branch that checks the
generated POM for missing versions in dependencies and uses the
information provided by the dependency management plugin to add those
back.
Fixes #1082
=> Add managed dependency versions to generated POM

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerLifecycleIntegrationTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1080
When we have a configuration like this:
```
container.setConcurrentConsumers(1);
container.setMaxConcurrentConsumers(1);
container.setConcurrency("2-5");
```
we fail with an assertion like
`'concurrentConsumers' cannot be more than 'maxConcurrentConsumers'`
* Change the order in the `SimpleMessageListenerContainer.setConcurrency()`
how we populate `maxConcurrentConsumers` and `concurrentConsumers`
**Cherry-pick to 2.1.x and 1.7.x**
=> GH-1080: SMLC: Fix concurrency configuration order

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleResourceHolder.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/RoutingConnectionFactoryTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1091
The DMLC can open a connection on the calling thread (e.g. `start()`, `setConsumersPerQueue()`).
When using a routing connection factory, the factory key is temporarily bound to the thread for
proper CF selection in connection listeners (e.g. `RabbitAdmin`).
This is disallowed if the calling thread is, itself, a listener container thread.
Add `push/pop` operations to `SimpleResourceHolder`.
=> GH-1091: Fix DMLC with Routing Connection Factory

spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/DeflaterPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/DelegatingDecompressingPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/InflaterPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
This is adding DeflaterPostProcessor and InflatorPostProcessor classes to the org.springframework.amqp.support.postprocessor as well as a few unit tests.  I did my best to follow the style and logic of how Gary coded the other PostpProcessor classes.
Related to this issue I created earlier today:
https://github.com/spring-projects/spring-amqp/issues/1094
=> Add DeflaterPostProcessor and InflatorPostProcessor classes

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitReturnTypesTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1093
AMQP-807 added support for generic return types; however this broke abstract
return types since the `__TypeId__` header was set to the abstract type.
If the return type is not a container type and represents an abstract class
or interterface use the concrete return type to construct the `JavaType`.
=> GH-1093: @RabbitListener fix abstract return type

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Docs in setUsePublisherConnection say this defaults to true since version 2.1 what, in my opinion, is not true
=> Update setUsePublisherConnection javadocs

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1106
`RabbitTemplate.invoke()` did not honor `usePublisherConnection`.
=> GH-1106: Fix Use Publisher CF with RT.invoke()

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessorTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/1108
`@RabbitListener.queues()` resolves `String[]` recursively.
AMQP-722 added support for multiple routing keys to `@queueBinding` but
did not add support for recursive resolution. This is required to support
constructs like `key = "#{'${my-app.amqp.routing-key}'.split(',')}"`.
=> GH-1108: @QueueBinding.key recursive resolution

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1113
Use `RabbitUtils` for all `basicCancel` calls, with try/catch for
all exceptions.
=> GH-1113: Clean up cals to basicCancel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ContainerCustomizer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ConsumerBatchingTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryTests.java, src/reference/asciidoc/amqp.adoc
- deprecate containerConfigurer `Consumer<C>` to more easily facilitate
Boot auto configuration.
=> Add ContainerCustomizer

src/reference/asciidoc/amqp.adoc
The return type for the following methods in documentation should be `Object` instead of `Message`.
```java
Message receiveAndConvert(long timeoutMillis) throws AmqpException;
Message receiveAndConvert(String queueName, long timeoutMillis) throws AmqpException;
```
=> Fix the wrong method return type in documentation

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererIntegrationTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1130
`RepublishingMessageRecoverer` - include the exception message length in the
truncation algorithm.
Note that the message is included in the stack trace.
If the stack trace + exception message would exceed the limit
- first truncate the message within the stack trace to 100 bytes
-- if the stack trace and original message still exceed the limit
-- also truncate the `X_EXCEPTION_MESSAGE` header to 100 bytes and
use the remaing space for stack trace
If, after truncating the message in the stack trace, there is room remaining
the full stack trace as well as the truncated message, re-truncate the
`X_EXCEPTION_MESSAGE` header to use the remaining available bytes.
examples:
message 150 bytes, stack trace 350 bytes, available 300 …
=> GH-1130: Repub Recoverer include ex. message size

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/InvocationResult.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1133
Currently, the target bean and method are populated only in the request
message and then only for a method-level listener.
- Populate the properties for class-level listeners
- Populate the properties on reply messages too
- Fix `RabbitTemplate` to invoke `afterReceivePostProcessors` when using
a reply container (bug).
**I will cherry-pick the template fix after the review/merge**
=> GH-1133: Add called bean/method to reply msg props

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessorTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1136
Note that this is a minimal implementation that avoids major refactoring
of the BPP.
Repeatable user meta-annotatiions are not supported.
In a future release we should perform that refactoring as well as supporting
`@Repeatable` user annotations.
Also restore the `stop()` with finally to fix `EnableRabbitTests.testProperShutdownOnException()`
which took 30 seconds to run after the finally was removed by
c1e31798961262795c4aa2b4bab3f0f67fedda26
=> GH-1136: Support Meta Annotations with AliasFor

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitOperations.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1140
`start()` and `stop()` methods are `final`, causing NPEs with CGLIB
proxies.
- remove `final` modifiers
- pull `Lifecycle` up to `RabbitOperations` so JDK proxies can be used
- add default no-op implementations for backward compatibility
Also implement `DisposableBean` so that reply containers are stopped.
=> GH-1140: RabbitTemplate and CGLIB Proxies

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/log4j2/AmqpAppenderTests.java, spring-rabbit/src/test/resources/log4j2-amqp-appender.xml
Resolves https://github.com/spring-projects/spring-amqp/issues/1148
Defer creation of all Spring static loggers from appender until the
appender is initialized.
The first logger (e.g. Spring Boot) initializes the static `LoggerContext`
field in `LogAdapter.Log4jLog`; this, in turn initializes the appender.
However, the appender references Spring objects that have static loggers.
This causes the `Log4jLog` CTOR to be called before the field is initialized,
causing an NPE.
Defer creation of all static loggers until the appender is fully initialized.
Tested with the log4j2 sample app.
Also add a test for async sends.
=> GH-1148: Log4jAppender - fix initialization cycle

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerRetryIntegrationTests.java
In preparation for https://github.com/spring-projects/spring-integration/issues/3172
Allow the inbound endpoint to detect if its listener container is configured
to return batches.
=> Add isConsumerBatchEnabled() to listener container

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java
- SI adds the listener after Spring has called APS
=> Move Batch Listener check to start()

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererTest.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1166
Occurred when the cause had a `null` message.
=> GH-1166: Fix NPE in RepublishMessageRecoverer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1169
Previously, the default was TLSv1.2 if the context was created by the
amqp-client, but 1.1 if the context was created by the factory bean.
=> Always default to TLSv1.2

build.gradle
Upgraade spring-doc-resources from version 0.2.0 to version 0.2.1
to get a bug fix (setting the display width for the HTML output).
=> Upgrade spring-doc-resources

spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/BrokerRunning.java, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/BrokerRunningSupport.java, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/RabbitAvailableCondition.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerCaptureTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyAndCaptureTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/TestRabbitTemplateTests.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/package-info.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1190
- Remove reference to `Assume` in `BrokerRunningSupport`
- Move example test cases to a new package so they can be easily copied/pasted
- Remove `assumeOnline` field - it looks like it was intended to support running
tests only if RabbitMQ is NOT running; but there was never any way to set it
to false
=> GH-1190: Remove reference to Junit4 Assume

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1194
Deferred channel closes were unconditionally returned to the cache.
Move the cache size check etc to `doReturnToCache`.
=> GH-1194: Fix cache limit with Pub Confirms channel

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1201
Support de-batching producer batches to a `List<Meessage>` with native
`BatchMessageListener`s; previously this was only possible with
`@RabbitListener` which does the debatching itself.
=> GH-1201: Native BatchMessageListener Support

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1201
The previous commit did not work with `ChannelAwareBatchMessageListener`.
Also add a test to get `List<o.s.a.c.Message>` in a `@RabbitListener` (which
exposed this issue).
=> GH-1201: Fix for ChannelAwareBatchMessageListener

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1215
Previously, the message converter would fall back to header type info
if the inferred type was abstract.
Furthermore, we did not examine container type content being abstract.
With a custom deserializer, abstract classes can be deserialized.
=> GH-1215: Allow Abstract Class Deserialization

spring-amqp/src/main/java/org/springframework/amqp/support/AmqpHeaders.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/MessagingMessageConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ContentTypeDelegatingMessageConverterIntegrationTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1219
The headers were mapped after message conversion.
This prevented using a `ContentTypeDelegatingMessageConverter` because
the content type was not set.
**cherry-pick to 2.2.x, 2.1.x, 1.7.x**
=> GH-1219: Fix header mapping for replies (@SendTo)

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1217
=> Configurable ResourceLoader for RabbitCFactoryBean

spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/RabbitListenerTestHarness.java, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/mockito/LambdaAnswer.java, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/mockito/LatchCountDownAndCallRealMethodAnswer.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/RabbitListenerProxyTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyAndCaptureTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerSpyTest.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/mockito/AnswerTests.java, src/reference/asciidoc/testing.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1226
https://github.com/spring-projects/spring-amqp/issues/1157 changed the way we spy
listeners - to support CGLIB proxies (e.g. `@Transactional`).
Instead of spying the listener, it mocks the listener and sets a default answer
to call the real method on the delegate.
This broke when users used other answers, such as those provided by the framework.
Change the provided answers to subclass `ForwardsInvocation`.
Also fix `ConcurrentModificationException` in `getExceptions()`.
=> GH-1226: Fix Test Harness

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java
Replaces https://github.com/spring-projects/spring-amqp/pull/1225
`manager.stop()` was never called to destroy the connection factory, preventing
JVM exit.
Also protect for re-connecting after stop (both appenders).
Tested with a Spring Boot application.
**cherry-pick to 2.2.x, 2.1.x, 1.7.x**
=> GH-1225: Fix Log4j2 Appender Termination

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PendingConfirm.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1230
We must guarantee that returns are delivered before confirms.
https://github.com/spring-projects/spring-amqp/issues/1055 changed the logic
to deliver on a different thread to avoid a deadlock in the amqp-client.
Since the executor service might have multiple threads, we added a latch to
ensure the return is delivered first.
Unfortunately, this was a one-shot latch and subsequent deliveries using the
same channel might arrive in the wrong order.
Move the latch to the `PendingConfirm` to reinstate in-order delivery.
=> GH-1230: Fix return/confirm delivery order

spring-amqp/src/main/java/org/springframework/amqp/support/converter/MessagingMessageConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ContentTypeDelegatingMessageConverterIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1236
The user may set the contentType to a `MimeType`.
Always use `toString()` when replacing the `contentType`.
**cherry-pick to 2.2.x, 2.1.x, 1.7.x**
=> GH-1236: Handle non-String contentType

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParser.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/resources/org/springframework/amqp/rabbit/config/spring-rabbit.xsd, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml, src/reference/asciidoc/amqp.adoc
Previously, only random address shuffling was supported; it is useful,
for scenarios such as using the RabbitMQ Sharding Plugin, to be able
to connect to multiple nodes in a deterministic manner.
=> Add Deterministic Address Shuffling

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1246
- called `queuesChanged()` twice
- didn't wait for old consumers to exit, causing problems with exclusive consumers
**I will back port, as needed**
=> GH-1246: SMLC: Fix addQueueNames

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/logback/AmqpAppender.java
`org.springframework.amqp.rabbit.logback.AmqpAppender.java`
```java
protected class EventSender implements Runnable {
@Override
public void run() {
try {
RabbitTemplate rabbitTemplate = new RabbitTemplate(AmqpAppender.this.connectionFactory)
while (true) {
final Event event = AmqpAppender.this.events.take();
MessageProperties amqpProps = prepareMessageProperties(event);
String routingKey = AmqpAppender.this.routingKeyLayout.doLayout(event.getEvent());
sendOneEncoderPatternMessage(rabbitTemplate, routingKey);
doSend(rabbitTemplate, event, event.getEvent(), name, amqpProps, routingKey);
}
}
catch (InterruptedException e) {
Thread.currentThread().interrupt();
}
}
}
...
```
Any exceptions in this `while(true){}` code block will be lost (except `InterruptedException`).
For example, when …
=> Catch exception when EventSender stopped

spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/AbstractCompressingPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/AbstractDecompressingPostProcessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/DelegatingDecompressingPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1251
Delimiter should be a comma and whitespace trimmeed.
Handle both delimiters in decompressors and add property for backwards compatibility.
**I will backport to 2.2.x with default `:`**
=> Fix Compressed contentEncoding Delimiter

spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1253
Misleading field name `standardCharset`. It was meant to convey that Jackson's default
charset (UTF-8) is being used and so we can convert directly to `byte[]`. Otherwise
we convert to `String` and then to `byte[]` using the configured charset.
Also, it was not set to `true` by default.
=> GH-1252: Jackson Converter Polishing

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1258
Call the handler for all `Error`s on container threads.
**I will do the cherry-pick; there will be conflicts**
=> GH-1258: Change OOMHandler to JavaLangErrorHandler

src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Supplement to https://github.com/spring-projects/spring-amqp/pull/1111
=> GH-891: Docs for Multi RabbitMQ Support

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/test/kotlin/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt
Similar to https://github.com/spring-projects/spring-kafka/issues/1631
The `DelegatingInvocableHandler` doesn't take into account a possible proxy
nature of the listener class.
* Fix `DelegatingInvocableHandler.setupReplyTo()` to deal with user class
which is origin for possible CGLib proxy for the proper annotations search
**Cherry-pick to 2.2.x**
=> Fix missing class-level `@SendTo` for CGLib proxy

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1269
Previously, a parameter annotated with a "foreign" annoation (e.g. `@Validated`)
would not be considered as an eligible payload conversion target; it must also
have been annotated with `@Payload`.
- remove the check for zero annotations
- add a check that the method is not annotated with both `@Payload` and `@Header`
- ignore if it does, with a warn log, to be consistent with previous behavior.
- in a future release we might consider this to be fatal.
=> GH-1269: @RabbitListener: Allow other Annotations

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, src/reference/asciidoc/amqp.adoc
- Allow the publishing connection factory to be explicitly set and be
any type
- Do not propagate properties when the factory is explicitly configured
=> Fix Sonar issues and other refactoring

src/reference/asciidoc/amqp.adoc
Currently AsyncRabbitTemplate's section title in documentation looks odd:
The proposed change will align styling of the section title
=> Fix Async Rabbit Template documentation section

spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverterTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1279
Regression: #1215
Test for abstract class should not be applied to container types, which can
be abstract.
=> GH-1729: Fix JSON Regression

.github/workflows/pr-build-workflow.yml
=> Use management tag for RabbitMQ image on GH actions

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitReturnTypesTests.java
For bean name properties that can have an expression, allow
the expression to evaluate to an instance of the desired
type instead of a bean name.
=> @RabbitListener property improvements

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CorrelationData.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/AmqpNackReceivedException.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecoverer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererWithConfirms.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/MessagingTemplateConfirmsTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests2.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests3.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererWithConfirmsIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1293
Add a subclass that waits for confirms and checks for returns.
=> GH-1293: Confirms/Returns with Republish Recoverer

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MissingQueueEvent.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1296
- Add `MissingQueueEvent`
- Fix detection of a deleted queue in recovery - previously incorrectly used the
absense of the queue in `consumersByQueue`, which can be empty if missing during
start
- Add an index to `SimpleConsumer`
- When adjusting consumer counts, look for gaps in the index sequence because reducing
the consumer count can remove any idle consumer.
- Change consumers to restart to a `Set` to avoid OOM when no broker
(see https://github.com/spring-projects/spring-amqp/pull/642)
- Unconditionally add consumers to `consumersToRestart`
=> GH-1296: Fix DMLC Recovery: Missing Queue at Start

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CorrelationData.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelTests.java
- NPE in deprecated `CorrelationData.getReturnedMessage()`.
=> GH-1293: Fix regression

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
Currently when `Error` is encountered while invoking direct message listener, default error handler terminates JVM without any information about the issue. My Spring application was shutdown and I had no clue why that happened. During debugging I discovered an exception which was caused by incorrect project dependencies:
`java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'`
I'm suggesting to log an error message before JVM is terminated.
@pivotal-issuemaster This is an Obvious Fix
=> Log error when direct message listener fails

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java
Related to https://stackoverflow.com/questions/66071476/impossible-nullpointerexception-springframework-rabbitmq-failed-to-invoke
When we have several pending confirms, we handle them concurrently
in the `doHandleConfirm()`.
The `afterAckCallback` can be set `null` in one thread and
another will fail with NPE after acquiring a monitor from the
`getPendingConfirmsCount()`.
* Extract a local variable for the `callback` inside an `if` block
* Initialize it with `this.afterAckCallback` only if
`getPendingConfirmsCount() == 0` is true,
and set `this.afterAckCallback` to null inside `synchronized (this)`
block
* Call `callback.accept(this)` when local variable is not `null`
and outside of `synchronized` for better performance on end-user callback
**Cherry-pick to 2.2.x**
=> Fix PublishCallCh.afterAckCallback race condition

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/MultiRabbitBootstrapConfiguration.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/MultiRabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerConfigurationSelector.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/RabbitListenerConfigUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/MockMultiRabbitTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/MultiRabbitBootstrapConfigurationTest.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/MultiRabbitListenerAnnotationBeanPostProcessorCompatibilityTests.java
- Creation of the **MultiRabbitBootstrapConfiguration**, activated via properties, since the default **RabbitListenerBPP** bean cannot be overridden with auto-config.
- Injection of the MultiRabbit **admin** to the **RabbitListener**, before it's processed by **RabbitListenerBPP**, so as to have the bean resolved and assigned to the **MethodRabbitListenerEndpoint**. It fixes an issue lately found on the order of loading where the **MultiRabbitAutoConfig** (at boot) was not being processed before **MultiRabbitBPP** starts the **postProcessAfterInitialization()**, which leads to bean not found.
- Move some configs to **RabbitListenerConfigUtils** as they are shared among Rabbit and MultiRabbit, as well as used in the boot.
=> Introducing MultiRabbit Bootstrap

.github/workflows/pr-build-workflow.yml, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ClientRecoveryCompatibilityTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/TransactionalEventListenerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1309
If the `RabbitTemplate` was called from a `@TransactionalEventListener`,
with phase `AFTER_COMMIT`, a transaction is "active", but synchronizations
are already cleared. It is too late to synchronize this transaction.
We end up with an orphaned `ResourceHolder` with pending transaction commits.
Don't bind the resource holder if synchronization is not active.
However, the proper solution, if users want to synchronize the rabbit transaction
with the global transaction, is to use the `BEFORE_COMMIT` phase.
See the discussion on the Github issue for more information.
=> GH-1309: Don't Bind Resource When Sync Not Active

.github/workflows/pr-build-workflow.yml, CONTRIBUTING.adoc, README.md, src/dist/README.md
=> Use current main branch in docs instead of master

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1312
With Direct Reply-To we can correlate the reply using the channel
instead of requiring the server to echo back the correlation id.
=> GH-1312: Correlation on Channel with Direct Reply

src/reference/asciidoc/amqp.adoc
Should be `DeclarableCustomizer` instead of `DeclarationCustomizer`.
=> DeclarableCustomizer - a small typo in the documentation

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryUtils.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerTxSynchTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1341
For more context see the issue description.
If commit or rollback fails during synchronization `afterCompletion`
cleanup code was not called.
=> GH-1341: Move Tx Synch Cleanup to a finally block

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/api/RabbitListenerErrorHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapterTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1339
Error handler was not called for conversion exceptions, preventing
the application frm returning some error to the caller for request/reply
processing.
=> GH-1339: Fix RLErrorHandler with Conversion Ex.

src/reference/asciidoc/index.adoc
Link the HTML to the PDF and vice-versa.
=> Add links to alternate documentation formats

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1347
Container starts and keeps trying to connect instead of honoring
the property.
=> GH-1347: DMLC Ignored Authentication Failures

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapterTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1339
Previous fix calls the error handler after a conversion exception, but
sending a reply returned by the eh (or returning the exception) caused
NPEs because the return logic referenced the inbound converted message.
=> GH-1339: Fix NPEs with returns after conversion ex

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateMPPIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1359
When the `RabbitTemplate` is configured with `afterReceivePostProcessors`
and uses the default internal `DirectReplyToMessageListenerContainer`, the
postprocessors are applied twice, once by the container and once by the
template.
The template should not propagate the post processors into the container.
=> GH-1359: After Receive Post Processor Invoked x2

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/StreamRabbitListenerContainerFactory.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/ConsumerCustomizer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java
- pass in the listener id, if available
- narrow to a specific interface to aid Boot auto configuration
- add null check
=> GH-1352: ConsumerCustomizer Improvements

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerParser.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerPlaceholderParserTests.java, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/rabbit-listener.properties, spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ListenerContainerPlaceholderParserTests-context.xml
Resolves https://github.com/spring-projects/spring-amqp/issues/1372
Do not split `queue-names` in the parser - leave it to Spring's type converter.
Also support SpEL in `queues`; a more elegant solution would require major
refactoring of the parser; so this is just a compromise.
=> GH-1732: Fix Listener Container Parser

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJackson2JavaTypeMapper.java, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/mockito/LatchCountDownAndCallRealMethodAnswer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CorrelationData.java, src/checkstyle/checkstyle.xml
- a checkstyle bug prevented detection of javadoc tag ordering
- `allowMissingJavadoc` is no longer available on `JavadocMethod`
(replaced by `MissingJavadocMethod`)
=> Upgrade checkstyle; fix violations

spring-amqp/src/main/java/org/springframework/amqp/core/Message.java, spring-amqp/src/test/java/org/springframework/amqp/core/MessageTests.java
Don't convert large message bodies to a `String` in `toString()`.
Set a limit (50) that can be modified by users.
Avoid possible OOM Errors.
=> Message toString() Improvement

build.gradle, gradle.properties, spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, x
Don't Log Converted Message With Projection
`toString()` cannot be invoked on the payload proxy created by
the projection factory.
Increase memory for builds.
=> Fix DEBUG Logging for Projection

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1406
Previously, if an MPP caused the last record in an ack to be skipped
two acks for the same deliveryTag would be sent causine a channel
shutdown.
There is no need to ack skipped records because the entire batch is
acked (with basicAck multiple=true).
=> GH-1406: Fix Possible Double Ack in Consumer Batch

spring-amqp/src/main/java/org/springframework/amqp/core/MessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/AbstractAdaptableMessageListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/HandlerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MonoHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/AsyncReplyToTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1409
Normally, when message has a fatal exception (such as message conversion)
`basicNack` with `multiple` true is used, to nack any previously unacked
messages (e.g. when using batch size to limit the ack traffic).
Even when using manual acks, fatal exceptions are nacked by the container
because the user does not have access to the message.
However, when using async replies, this has the side effect of nacking
unprocessed messages.
Detect whether async replies are being used and only nack individual
records that cause fatal exceptions.
Also, coerce the `AcknowledgeMode` to `MANUAL` for such listners.
Add a test for both containers; send a good message followed by a
bad one without actually completing the reply future.
After …
=> GH-1409: Fix Nacks for Async Replies

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitMessagingTemplateTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1412
The use of the `defaultDestination` is not correct when the template is
used for both sends and receives because it is a queue name for receives
and a routing key for sends.
Add a new option to use the template's configured default receive queue
for receive only methods. False by default to avoid a breaking change;
it should be true by default in a future release.
=> GH-1412: Fix Messaging Template

src/reference/asciidoc/amqp.adoc
RoutingConnectionFactory is not a ConnectionFactory
=> fix multi-rabbit example

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessorTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1422
Broker-named queues did not work with `@RabbitListener` because the BPP
only passed the name of the queue bean, not the bean itself, into the
endpoint.
Support bean injection; fall back to the previous behavior if a mixture
of beans and names are encountered (the containers don't support both
types of configuration).
Add a note to the javadoc to indicate that broker-named queues are not
supported via `queuesToDeclare` and `bindings` properties; such queues
must be declared as discrete beans.
=> GH-1422: @RabbitListener: Fix Broker-Named Queues

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractRoutingConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/RoutingConnectionFactoryTests.java
There is a little inconsistency in `AbstractRoutingConnectionFactory` that this PR aims to fix.
```
@Bean
ConnectionFactory connectionFactory() {
return new MyAbstractRoutingConnectionFactory(new HashMap<>() {{
put("first", newPooledChannelConnectionFactory());
put("second", newCachingConnectionFactory());
}});
}
static class MyAbstractRoutingConnectionFactory extends AbstractRoutingConnectionFactory {
MyAbstractRoutingConnectionFactory(final Map<Object, ConnectionFactory> factories) {
factories.forEach(this::addTargetConnectionFactory);
}
@Override
protected Object determineCurrentLookupKey() {
return null;
}
}
```
in this case, `AbstractRoutingConnectionFactory#afterPropertiesSet` throw a `java.lang.IllegalArgumentException: At least one target factory (or default) is required` because …
=> add checkConfirmsAndReturns in addTargetConnectionFactory

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1439
Do not store pending confirms/returns if `RabbitTemplate` has confirms
enabled but the factory does not support confirms.
**cherry-pick to 2.4.x, 2.3.x**
Suggest review with `?w=1`
=> GH-1439: Fix Memory Leak with Misconfiguration

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1441
Previously, `MessageHeaders` had to be annotated with `@Headers` so that
it was ignored during payload parameter resolution; otherwise it caused
ambiguity.
Ignore `MessageHeaders` even when not so annotated.
Also fix some tests that were checking the same topic and count down latch so were
unconditionally passing.
Change one of those tests to verify the fix.
**cherry-pick to 2.4.x, 2.3.x**
=> GH-1441: Fix Payload Detection with MessageHeaders

src/reference/asciidoc/amqp.adoc
Fixes a typo in the reference documentation.
=> Fix typo in amqp.adoc

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1452
While not a problem with connection factories provided by the framework
(which all ignore `close()`) the code should properly close the connection
after use.
**cherry-pick to 2.4.x, 2.3.x**
=> GH-1452: Close Connection in checkMissingQueues

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/StreamRabbitListenerContainerFactory.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/adapter/StreamMessageListenerAdapter.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/retry/StreamMessageRecoverer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/retry/StreamRetryOperationsInterceptorFactoryBean.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/retry/package-info.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/StreamListenerContainerTests.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/AbstractRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/BaseRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatelessRetryOperationsInterceptorFactoryBean.java, src/reference/asciidoc/stream.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1455
Add an advice chain to the stream listener container and its factory.
Add a `StreamMessageRecoverer` for native stream messages.
Add a retry interceptor to work with native stream messages.
(What's New? will conflict so I left it out - will polish it in both branches after merge).
=> GH-1455: AdviceChain on Stream Listener Container

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/MicrometerHolder.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBeanTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MicrometerHolderTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1459
=> GH-1459: Improve MeterRegistry Discovery

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/SimpleConnection.java
=> chore: remove redundant space is string representation

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/SuperStream.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/config/SuperStreamProvisioningTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/support/AbstractIntegrationTests.java, src/reference/asciidoc/stream.adoc
See https://github.com/spring-projects/spring-amqp/issues/1465
Inspired by https://github.com/rabbitmq/rabbitmq-stream-java-client/blob/29b1a3eca72c8e3f719db4fd9fafdf503f37ea20/src/test/java/com/rabbitmq/stream/impl/TestUtils.java#L244-L276
cc/ @acogoluegnes
=> GH-1465: Part 1: Provision Super Streams over AMQP

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/batch/SimpleBatchingStrategy.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplateTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1474
When consuming the whole debatched batch as a list, all messages
had the `lastInBatch` property set to true.
Clone the message properties for the last record.
=> GH-1474: Fix MessageProperties.lastInBatch

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate2.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/RabbitConverterFuture.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/RabbitFuture.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/RabbitMessageFuture.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/TimeoutTask.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate2Tests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ComplexTypeJsonIntegrationTests.java
- to aid migration from 2.4.x to 3.0.x so that the return types will not change
=> GH-1473: Move RabbitFutures to Top Level Classes

spring-amqp/src/main/java/org/springframework/amqp/core/AsyncAmqpTemplate2.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamOperations.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamOperations2.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate2.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate2.java, src/reference/asciidoc/appendix.adoc, src/reference/asciidoc/stream.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1480
Also reinstate deprecated `AsyncAmqpTemplate2`.
=> GH-1480: Switch to CompletableFuture in s-r-stream

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/BatchMessagingMessageListenerAdapterTests.java, src/reference/asciidoc/amqp.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1489
- allow listeners to consume `Collection<?>` as well as `List<?>`
- detect a non-batch listener method in the batch adapter
- coerce `batchListener` to `true` when `consumerBatchEnabled` is true
=> GH-1489: Batch RabbitListener Improvements

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1487
=> AsyncMessageProcessingConsumer countdown when the container is not active

spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/RabbitListenerTestHarness.java, spring-rabbit-test/src/test/java/org/springframework/amqp/rabbit/test/examples/ExampleRabbitListenerCaptureTest.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1494
Capture mode failed to capture arguments/result/exception if multiple
`@RabbitListener` annotations present.
=> GH-1494: Fix Test Harness with @Repeatable

build.gradle, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/SuperStreamSACTests.java, src/reference/asciidoc/quick-tour.adoc, src/reference/asciidoc/stream.adoc, src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1465
Add support for single active consumers on super streams.
Stop containers in test.
Use Snapshot Repo
Use snapshot repo; use TestContainers.
=> GH-1465: Part II - Super Stream SAC

build.gradle, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/AbstractTestContainerTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/config/SuperStreamProvisioningTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/RabbitListenerTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/SuperStreamConcurrentSACTests.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/listener/SuperStreamSACTests.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/NodeLocatorTests.java
If a node was returned by the REST call and the node was not in the map of nodes to addreses, the loop exited early.
The incorrect variable was being tested (never null).
Also add a more sophisticated integration test - using 2 brokers, ensure that the correct broker is located for the queue.
**I will back port to 2.4.x after merge**
=> GH-1419: Fix Early Exit in NodeLocator

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1477
Only log the stack trace on the first failure.
Tested with a Boot app and stop/start/stop the broker.
=> GH-1477: Reduce Log Noise While Broker Down

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1524
Channel was always physically closed.
=> GH-1524: Fix ThreadChannelCF with Transactional

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/1533
Allow setting consumer arguments when using non-zero receive timeouts using the `RabbitTemplate`.
=> GH-1533: Template Receive with Consumer Args

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MonoHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/1550
=> GH-1550: Fix Mono Return Type Detection

build.gradle, spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/AbstractTestContainerTests.java
Disable the tests, if Docker is not available.
=> Fix Testcontainer Tests With No Docker Running

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
=> Run callback for shutdown also when container is already shut down

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2425
Assume connection problem when no cause.
=> GH-2425: Fix NPE in ACFactory.shutdownCompleted

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/QueueDeclarationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2432
When a container starts; it looks to see if the context contains a queue bean for any of its queues and requests the admin to redeclare the infrastructure.
However, if the queue is declared within a `Declarables`, the check is not performed and therefore the queue is not declared.
Add a check for `Declarables` beans.
=> GH-2432: Fix Redeclaration of Declarables

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java
Issue link: [#2428](https://github.com/spring-projects/spring-amqp/issues/2428)
Fixes an issue when manual declarations are not being redeclared upon connection recovery, when application context has not been set
=> fix: #2428 - recovery manual declarables without application context

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandler.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/DelegatingInvocableHandlerTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2437
Failure to find a `@RabbitHandler` method for the payload must be treated as a fatal exception to avoid an infinite loop.
Also, fix CREH cause traversal to stop when **any** fatal exception is found. Previously, traversal only stopped for the original subset of exceptions.
=> GH-2437: Fix Fatal When No Matching RabbitHandler

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2456
When spying a `@RabbitListener` bean, duplicate methods are resolved as well as duplicate class level `@RabbitListener` annotations.
**cherry-pick to 2.4.x** (will require instanceof polishing for Java 8)
=> GH-2456: Suppress Duplicate Annotations with Spy

src/reference/asciidoc/amqp.adoc
Alignment based on
> The default `addressShuffleMode` in `AbstractConnectionFactory` is now `RANDOM`. 
From [whats-new.adoc](https://github.com/spring-projects/spring-amqp/blob/5451bfe000e7f2a8efecf4e0df7bdfd1915e9148/src/reference/asciidoc/whats-new.adoc?plain=1#L53)
=> Aligned client connection order reference.

src/reference/asciidoc/stream.adoc
ConvertableFuture -> CompletableFuture
=> Fix typo in stream.adoc

src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2472
=> GH-2472: Doc SSL with Java or Boot

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java, src/reference/asciidoc/amqp.adoc
Resolves https://github.com/spring-projects/spring-amqp/issues/2482
`forceStop` means stop after the current record and requeue all prefetched.
Just close the channel - canceling the consumer first causes a race condition which could allow another exclusive or single-active consumer to start processing while this container is still running.
Also support async stop on DMLC (previously only available on the SMLC).
=> GH-2482: Option for Containers to Stop Immediately

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitConnectionFactoryBean.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2495
Although the factory bean has...
```java
/**
* Access the connection factory to set any other properties not supported by
* this factory bean.
* @return the connection factory.
* @since 1.7.14
*/
public ConnectionFactory getRabbitConnectionFactory() {
```
...this new CF property could be a breaking change for users that configure the factory bean using XML.
=> GH-2495: Add maxInboundMessageBodySize to RCFB

spring-amqp/src/main/java/org/springframework/amqp/core/AmqpAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2498
Manual redeclaration logic did not account for an exchange having the same name as a queue.
**back port to 2.4.x will have conflicts and requires instanceof polishing** (I will do it after merge).
=> GH-2498: Fix Manual Redeclaration With Dup. Names

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2511
When inactive containers are present, the `DefaultLifecycleProcessor` hangs for (default) 30 seconds waiting for containers to stop.
When `stop(Runnable)` is called, the callback was not run if the container was not running; this was a regression caused by 1fdfe650ac1b6b28f11543af026c94b5128f1ba5.
=> GH-2511: Fix Container Stop Regression

build.gradle
This sets the path sensitivity to relative for the `sourceDir` property of the `asciidoctorPdf` task. Previously, the full absolute path to the source directory would be considered as an input to the task. This would cause a local build cache miss when executing the task from two different directories or a remote build cache hit given that the paths to the sources directory on CI and for local developers will undoubtedly be different.
You can recreate this with the [Gradle Enterprise Build Validation Scripts](https://github.com/gradle/gradle-enterprise-build-validation-scripts) using the following command:
```shell
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/spring-projects/spring-amqp \
-t asciidoctorPdf \
-c 31834589d727b697833ad5ef38117555dc9a848b …
```
=> Output of `asciidoctorPdf` can be pulled from cache when run on machines with different checkout directories

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java
The framework is intended for use with Spring Framework 5.3.
However, this change was the only thing preventing it being used with 5.2.
=> GH-2456: (Re) Support Spring Framework 5.2

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java, spring-rabbit/src/test/kotlin/org/springframework/amqp/rabbit/annotation/EnableRabbitKotlinTests.kt
Resolves https://github.com/spring-projects/spring-amqp/issues/2532
The presence of the parameter caused the inferred type to be set to `null` due to ambiguous parameters present.
It must be considered an ineligible type when inferring conversion types.
**cherry-pick to 3.0.x (#2533), 2.4.x (#2534)**
=> GH-2532: Ignore Kotlin Continuation Parameter

spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/SuperStreamBuilder.java, spring-rabbit-stream/src/test/java/org/springframework/rabbit/stream/config/SuperStreamConfigurationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/FixedReplyQueueDeadLetterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplatePublisherCallbacksIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererWithConfirmsIntegrationTests.java
Resolves https://github.com/spring-projects/spring-amqp/issues/2552
Variables map to Erlang ints which are 8 bytes, so need to be long in Java.
=> GH-2552: Fix Builder Argument Types maxLength etc

.gitignore, spring-amqp/src/main/java/org/springframework/amqp/core/AbstractDeclarable.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/TestRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/LocalizedQueueConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PublisherCallbackChannelImpl.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/ThreadChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BatchingRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/BrokerEventListener.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/RoutingConnectionFactoryTests.java
- replace all trivial occurrences of synchronized block by Reentrant locks. 
Resolves #2481
=> [WIP] Replace trivial synchronized blocks with  reentrant locks

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/ListenerContainerFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/SimpleRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java, src/reference/antora/modules/ROOT/pages/amqp/containerAttributes.adoc
Fixes https://github.com/spring-projects/spring-amqp/issues/2601
stop to waiting next message and execute listener when batchReceiveTimeout is timed out.
=> GH-2601: Add a batchReceiveTimeout

settings.gradle
- [com.gradle.enterprise](https://plugins.gradle.org/plugin/com.gradle.enterprise) from 3.14.1 to 3.16.2
Based on commits in spring-framework repo, internally spring team should support latest Gradle Enterprise plugin:
- Commit with note that only 3.15 version is supported: spring-projects/spring-framework@e3f185a696b0d6ca017a83366f24ed692573d14e 
- Commit with 3.16 version: spring-projects/spring-framework@b7e4fa16cae5f5a45fd661c51d558c8b9e5c39ae
=> Upgrade Enterprise Gradle Plugin

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java
=> Make sure ReceivedDelay is non-negative

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java
Refactored the getOrSetCorrelationIdAndSetReplyTo method for improved readability and code organization. Merged the declaration and initialization of 'correlationId' into a single line. Ensured the logic remains unchanged. No functional changes introduced.
=> Refactor getOrSetCorrelationIdAndSetReplyTo method

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactoryTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java
GH-2572 Do not close channel when `ConfirmType.SIMPLE` is used for publisher confirmations.
See #2571 (discussion) and #2572 (issue) for reference.
=> GH-2572 Treat ConfirmType.SIMPLE same as ConfirmType.CORRELATED

src/reference/antora/modules/ROOT/nav.adoc, src/reference/antora/modules/ROOT/pages/amqp/broker-configuration.adoc, src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/micrometer-observation.adoc, src/reference/antora/modules/ROOT/pages/amqp/transactions.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/changes-in-1-6-since-1-5.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/message-converter-changes-1.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/message-converter-changes.adoc, src/reference/antora/modules/ROOT/pages/sample-apps.adoc, src/reference/antora/modules/ROOT/pages/stream.adoc
I update some reference links.
I also delete `message-converter-changes-1.adoc` because I think `message-converter-changes-1.adoc` and `message-converter-changes.adoc` are the same.
Please check again and tell me if I miss something.
=> Update Reference  Links

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainer.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerSMLCTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ExternalTxManagerTests.java
Run checkAfterCompletion to the SimpleMessageListenerContainer. That allows to be notified when there is an issue with the commit.
See the [original discussion ](https://github.com/spring-projects/spring-amqp/discussions/2758) and [issue](https://github.com/spring-projects/spring-amqp/issues/2805) for context.
=> GH-2805 Add a checkAfterCompletion to SimpleMessageListenerContainer.

spring-amqp/src/main/java/org/springframework/amqp/core/MessageProperties.java, spring-amqp/src/main/java/org/springframework/amqp/support/AmqpMessageHeaderAccessor.java, spring-amqp/src/main/java/org/springframework/amqp/support/SimpleAmqpHeaderMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJackson2MessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/RemoteInvocationAwareMessageConverterAdapter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/RemoteInvocationResult.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/SerializerMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/SimpleMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/postprocessor/AbstractDecompressingPostProcessor.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/AllowedListDeserializingMessageConverterTests.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/config/StreamRabbitListenerContainerFactory.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java, spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/support/converter/DefaultStreamMessageConverter.java, spring-rabbit-test/src/main/java/org/springframework/amqp/rabbit/test/TestRabbitTemplate.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/BaseRabbitListenerContainerFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/config/StatelessRetryOperationsInterceptorFactoryBean.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/PooledChannelConnectionFactory.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/RabbitUtils.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectReplyToMessageListenerContainer.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/RabbitExceptionTranslator.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/RabbitListenerContainerFactoryIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MessageListenerContainerErrorHandlerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerIntegration2Tests.java
I think it's more concise. Please tell me if I miss something
=> Apply pattern matching

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/micrometer/RabbitListenerObservation.java, spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/micrometer/RabbitTemplateObservation.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/support/micrometer/ObservationIntegrationTests.java
closes #2814
added message.destination.name and message.rabbitmq.destination.routing_key as new tags for RabbitTemplateObservationConvention 
added messaging.rabbitmq.message.delivery_tag and  message.destination.name to RabbitListenerObservationConvention
=> RabbitTemplate and RabbitListener add opentelemetry tags

src/reference/antora/modules/ROOT/pages/amqp/sending-messages.adoc
Just fixing a missing empty space.
=> Fix typo in sending-messages.adoc

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java
Previously, conversion errors in AsyncRabbitTemplate lead to AmqpReplyTimeoutException
Fixes https://github.com/spring-projects/spring-amqp/issues/2478
https://github.com/spring-projects/spring-amqp/issues/2478#issuecomment-2543745530
=> GH-2478 Handle conversion exception in AsyncRabbitTemplate

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/MultiRabbitListenerAnnotationBeanPostProcessor.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/MockMultiRabbitTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/2809
=> Fix containerFactory SpEL Resolution

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverterTests.java
Fixes https://github.com/spring-projects/spring-amqp/issues/2949
The handling of `retryCount` is moved into `convertHeadersIfNecessary()`, so that we can still return a `Collections.emptyMap()` if there are no headers in the source `MessageProperties` and no `retryCount` to add.
=> GH-2949: Fix retryCount handling

README.md
Since the switch to the `maven-publish` plugin (instead of the deprecated `maven` plugin)
in 48e816d0a901893ed50a1fcd0c74009d3d0bee8c, the correct way to publish to a local Maven repository is to use the `publishToMavenLocal` task.
This updates this in the README, and also changes to wording from "Maven cache" to "Maven repository" (which is more in line with Maven terminology).
See the documentation for [the Maven Publish plugin here](https://docs.gradle.org/current/userguide/publishing_maven.html).
=> Fix README on publishing to local Maven

src/reference/antora/modules/ROOT/pages/amqp/broker-configuration.adoc
Cannot find the constants (QUEUE_NAME/QUEUE_MESSAGE_COUNT/QUEUE_CONSUMER_COUNT) in RabbitTemplate
Fixes https://github.com/spring-projects/spring-amqp/issues/2956
These constants are actually defined in `RabbitAdmin`.
=> Fixes issue-2956

spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java
It would be nice to have `StreamListenerContainer.getStreamName()` method to fulfill need to dynamically stop/start listeners in reaction of broker events.
Let's say I need to react to RabbitMQ broker events of `queue.created` / `queue.deleted` ([see](https://www.rabbitmq.com/docs/event-exchange#rabbitmq-broker) ~ name of queue is sent in event) and I need to start and stop listeners, which are assigned to these streams. Currently I need to create an extra map of `listenerId` to `streamName` OR include streamName  in `listenerId` (e.g. `listener:{streamName}`) to be able to carry our operations on listener.
A simple getter for `streamName` on `StreamListenerContainer` would allow me to react to these changes dynamically without extra code effort.
An concise example with …
=> Add convenient getter for stream name

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverterTests.java
We had an issue in our system trying to consume a message from RabbitMQ that contained an `x-death` header, with `count` value typed as Integer. This caused a ClassCastException in https://github.com/spring-projects/spring-amqp/blob/355be1ee4c20dd1179c6eed59bb43fac5d18db6b/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java#L150
The reason the `count` value was an int and not a long is that we were storing headers in an internal database as part of a recovery process, and the typing was slightly changed during serialisation / deserialisation.
We propose this pull request to make the reading process of the `count` field in `x-death` header safer.
=> Read x-death count in a safer way

src/reference/antora/modules/ROOT/pages/amqp/resilience-recovering-from-errors-and-broker-failures.adoc
=> Improve Javadoc and attribute annotation

src/reference/antora/antora-playbook.yml, src/reference/antora/modules/ROOT/pages/amqp/connections.adoc
Current Reference
https://docs.spring.io/spring-amqp/reference/4.0-SNAPSHOT/amqp/connections.html
I've updated the code example and also replaced the outdated`NodeLocator` example.
I think we can apply the `configprops` tag to display the properties or yaml file, in the code block below the 'Spring Boot application file (`.yaml` or `.properties`)' section shown in the image.
The result
=> Improve connections document

src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/idle-containers.adoc, src/reference/antora/modules/ROOT/pages/logging.adoc, src/reference/antora/modules/ROOT/pages/rabbitmq-amqp-client.adoc, src/reference/antora/modules/ROOT/pages/stream.adoc
=> Improve document example

README.md
=> Update contributor section

build.gradle, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJacksonMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/AbstractJavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/DefaultJacksonJavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/Jackson2JsonMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/JacksonJavaTypeMapper.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/JacksonJsonMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/JacksonProjectingMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/JacksonUtils.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/JacksonXmlMessageConverter.java, spring-amqp/src/main/java/org/springframework/amqp/support/converter/ProjectingMessageConverter.java, spring-amqp/src/test/java/org/springframework/amqp/support/SimpleAmqpHeaderMapperTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/ContentTypeDelegatingMessageConverterTests.java, spring-amqp/src/test/java/org/springframework/amqp/support/converter/JacksonJsonMessageConverterTests.java, spring-amqp/src/test/resources/org/springframework/amqp/support/converter/JacksonJsonMessageConverterTests-context.xml, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/AsyncListenerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/ComplexTypeJsonIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitBatchJsonIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitReturnTypesTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/OptionalPayloadTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/AsyncReplyToTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/BatchMessagingMessageListenerAdapterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapterTests.java, src/reference/antora/modules/ROOT/pages/amqp/message-converters.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/changes-in-2-1-since-2-0.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/changes-in-2-2-since-2-1.adoc, src/reference/antora/modules/ROOT/pages/appendix/previous-whats-new/changes-in-3-0-since-2-4.adoc, src/reference/antora/modules/ROOT/pages/sample-apps.adoc, src/reference/antora/modules/ROOT/pages/whats-new.adoc
Fixes: https://github.com/spring-projects/spring-amqp/issues/3088
* Manage `tools.jackson` dependencies, similar way we do for Jackson 2
* Add Jackson 3 counterparts for existing Jackson 2 based classes. Technically, that is mostly just a copy/paste of existing classes, but with `tools.jackson` API adjustments
* Fix `AbstractJacksonMessageConverter` to catch not only `IOException`, but also `JacksonException`
* Migrate tests and docs to use new classes
* Deprecate Jackson 2 based classes
=> GH-3088: Add Jackson 3 support; deprecate Jackson 2

spring-amqp/src/test/java/org/springframework/amqp/support/converter/SimpleMessageConverterTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/ListenerContainerParserTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/config/MismatchedQueueDeclarationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/ConnectionFactoryLifecycleTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/connection/SSLConnectionTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitAdminTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/core/RabbitTemplateTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/BlockingQueueConsumerIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/ErrorHandlerTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/JavaConfigFixedReplyQueueTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpointTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/retry/RepublishMessageRecovererWithConfirmsIntegrationTests.java, spring-rabbit/src/test/java/org/springframework/amqp/rabbit/transaction/RabbitTransactionManagerIntegrationTests.java
=> Use `assertThatException` for exception test

spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/DirectMessageListenerContainer.java
Description:
This PR addresses issue #3122 by changing the log level for <i><b>MessageRejectedWhileStoppingException</b></i>  in 
<i><b>DirectMessageListenerContainer</b></i>. Previously, this exception was always logged at the error level, even though it is expected during an orderly shutdown and does not indicate a real error. Now, when this exception occurs, it is logged at the info level, reducing unnecessary error noise in logs.
Related Issue:
Fixes #3122
Details:
In <i><b>callExecuteListener</b></i>, exceptions of type <i><b>MessageRejectedWhileStoppingException</b></i> are now logged at info level. All other exceptions continue to be logged as errors.
=> Fixed issue #3122
